### ISSUE TITLE
Reduce Performance Impact of Running the Agent

### ISSUE THREAD

**Issue by wrumsby** [newrelic/newrelic-browser-agent#101]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

When monitoring some of our pages using [Calibre](https://calibreapp.com/) (which essentially runs [Lighthouse](https://developers.google.com/web/tools/lighthouse) in a lab) we can see nr-loader-spa sometimes blocking > 5s of main thread execution.

We are including the browser agent on our page with the following HTML:

```html
<script type="text/javascript">
(function () {
window.NREUM\|\|(NREUM={});
NREUM.init={distributed_tracing:{enabled: true,cors_use_newrelic_header: true,cors_use_tracecontext_headers:true,allowed_origins:[]},privacy:{cookies_enabled:true}};
NREUM.loader_config={accountID:"OUR_ACCOUNT_ID",trustKey:"OUR_ACCOUNT_ID",agentID:"OUR_APPLICATION_ID"};
NREUM.info={licenseKey:"OUR_LICENSE_KEY",applicationID:"OUR_APPLICATION_ID",agent:"https://OUR_CDN_DOMAIN/nr-spa.1210.js"};
}());
</script>
<script src="https://OUR_CDN_DOMAIN/nr-loader-spa.1210.js"></script>
```

To be fair this is running on a particularly slow page, elsewhere we only see a blocking time of 145ms.

## Desired Behavior

Ideally we want as little blocking time as possible, or perhaps some insight into why this might be taking so long in this case.

## Possible Solution

We've started using the style above as documented in this project's README because our apps are single page apps and we can't include the snippet via server-side monitoring and we found that the [snippets provided by the old REST API](https://rpm.newrelic.com/api/explore/browser_applications/list) seemed out of date.

Potentially we could change our script that generates the above HTML to instead inline `nr-spa.1210.js`, though in our trace it doesn't seem like _loading_ the script is the issue.

I'm not sure if it would be workable to delay instantiation of the agent and simply collect data until there doesn't seem to be a lot of other activity.

## Additional context

The Calibre trace is emulating desktop Chrome running over a cable connection; we have other tests using a similar profile that don't experience these long blocking times.

**Comment by aubreymasten** [comment]
@wrumsby we do the best we can to minimize the performance impact of the agent but we are aware the agent has some overhead, especially on certain pages when using the SPA agent. If you’d be willing to talk a little about your use case here, I could try and clarify what’s causing the issue.

What is it that makes this page where you're seeing 5+ seconds of blocking time so slow in the first place, when the agent isn't installed?

The other option, if there's sensitive information surrounding this page, would be to open a support ticket to try and clarify what's happening. We work pretty closely with Technical Support and can hopefully get you some answers that way as well.

**Comment by aubreymasten** [comment]
Hey @wrumsby, thanks for letting us know. If there are any other details you want to share about ho you changed to page to improve performance we'd love to hear but in the meantime I'm going to close this issue.
