### ISSUE TITLE
Cannot read properties of undefined (reading 'stopTimer')

### ISSUE THREAD

**Issue by Pranav2111** [newrelic/newrelic-browser-agent#1095]
I am using browser agent for my Next JS application.
I am getting this error **_(Cannot read properties of undefined (reading 'stopTimer'))_** reported on my sentry very frequently.

**Comment by patrickhousley** [comment]
@Pranav2111 we need more information to go on. What version of the agent are you using? Is this the NPM package or how is the agent installed? What version of node, npm, nextjs, etc? Drop a copy of your package.json and code where you are instrumenting the agent if it is the npm package. Whats the stack trace for the error? Please provide as much detail as possible when reporting issues to open source projects. Thanks.

**Comment by cwli24** [comment]
We had another report of this same issue, and I suspected the area of source of it, but thank you for giving us the trace to confirm! Will be spinning up a bug ticket for this.

**Comment by lluchez** [comment]
We are encountering the same issue, which started to happen on June 27 in our React App.

**Comment by jaohaohsuan** [comment]
We have been encountering the same issue since June 28  in Angular 17 app.

```
T.abortin https://js-agent.newrelic.com/nr-spa-1.261.1.min.js at line 2 : 65690

n.<anonymous>in https://js-agent.newrelic.com/nr-spa-1.261.1.min.js at line 2 : 61759
Object.emitin inline code at line 37 : 9898
anonymousin https://js-agent.newrelic.com/nr-spa-1.261.1.min.js at line 2 : 94242
```

**Comment by zboris** [comment]
The same error appears for the nr-spa.1.261.2 started 27 of June as well

<img width="1362" alt="image" src="https://github.com/newrelic/newrelic-browser-agent/assets/19600767/f1a9d0c6-7e18-46c6-98de-49f2842aa88c">

**Comment by zboris** [comment]
this error is going alongside with `undefined is not an object (evaluating 'this.scheduler.stopTimer')` error as well which happens in Chrome and Safari on Mac only.

**Comment by zboris** [comment]
i guess line 208 in the unminified code should be `this.scheduler?.stopTimer()` ?

**Comment by YesThatAllen** [comment]
We've been getting this error sporadically starting June 27 at 3:34 AM US/Central. (Didn't seem high priority given the low % of page loads it was happening on.)


```
Unhandled error
TypeError: Cannot read properties of undefined (reading 'stopTimer')
Location
https://js-agent.newrelic.com/nr-spa-1.261.1.min.js:2 - T.abort
```

Today we started getting this slightly different message:

```
Unhandled error
TypeError: this.scheduler is undefined
Location
https://js-agent.newrelic.com/nr-spa-1.261.2.min.js:2 - abort
```


> we need more information to go on. What version of the agent are you using?

Just `newrelic_rpm (9.8.0)`

> Is this the NPM package or how is the agent installed?
> What version of node, npm, nextjs, etc?

`nodejs 16`
`yarn 1.22`

Although, any tooling is being injected by `newrelic_rpm` which we installed ~3 months ago at v 9.8.0. (We'll look at updating it to 9.11 this week, but that seems unrelated in our case)

**Comment by rylanb** [comment]
We've been seeing quite a bit of these in the last week, which is clogging up our error notifications a bit. I cannot see the JIRA issue linked to see what the status is. 

Thanks for working on this, either way!

**Comment by cwli24** [comment]
This is the top of our list this week, so please wait for a patch in the next few days.
