### ISSUE TITLE
Automatically pull in config from application settings

### ISSUE THREAD

**Issue by paulwalko** [newrelic/newrelic-browser-agent#1106]
Currently the config must be manually specified. This can be a fairly tedious process since it involves extracting the settings from the HTML snippet in the newrelic console each time settings are changed. This can lead to the settings in the console being inconsistent from the settings manually specified in the javascript config if they are not perfectly transcribed.

## Summary

It would be nice if rather than having to manually extract config from the HTML snippet, this config was automatically pulled from newrelic. This seems to be already done with the APM browser injection method, so it seems like it should be possible here too.

## Desired Behavior

I would like to be able to call some API endpoint, specify the necessary tokens and entity IDs etc, and in return get the config settings for the application.

## Possible Solution

Expose an API endpoint that returns the config for a given application, specifically the `init`, `loader_config`, and `info` settings. Alternatively, add some function within this library to automatically pull in the settings from a given application.

## Additional context

Testing or changing features in the newrelic console requires a significant amount of effort to do, in comparison with the APM browser injection which pulls in the config settings automatically.

**Comment by patrickhousley** [comment]
Hi @paulwalko This is actually already possible with our GraphQL APIs. [Here](https://docs.newrelic.com/docs/apis/nerdgraph/examples/browser-monitoring-config-nerdgraph/#retrieve-app-config) is a doc that can help you implement this. Keep in mind it requires an API key to access these APIs and those keys should not be exposed publicly. However, you could integrate this into your build or CI/CD process in some way, as long as you do not expose the key. Please let us know if you need further assistance.
