### ISSUE TITLE
Use Client Hints API instead of `navigator.userAgent` when possible

### ISSUE THREAD

**Issue by martinkuba** [newrelic/newrelic-browser-agent#114]
## Summary

The agent is currently calling `navigator.userAgent` in a few places. This causes a warning in Chrome DevTools (Issues tab) starting with version 92. Chrome is gradually reducing the information available in the legacy User Agent API and moving to client hints.

The Client Hints API to use is `navigator.userAgentData`.

## Desired Behavior

Agent does not cause Chrome to display a warning message about the User Agent API in DevTools Issues.

## Possible Solution

Use `navigator.userAgentData` (when available) instead of `navigator.userAgent`.

**Comment by martinkuba** [comment]
It's so far only implemented in Chromium browsers, but I think likely to be adopted by others in the future.

UA can be spoofed (like any header), but in the context of the browser agent script, it would need to be modified en route (after the agent request is sent out), which we do not have control over. With that said, I don't think this is a real issue for data we receive from customers.

Is it possible to use feature detection for things like browser version and platform?

**Comment by cwli24** [comment]
Hmm, that's unfortunately. I tried to find some examples but despite the caveat against UA usage, it seems it's just the common way to go. The closest thing to feature detection is [this post](https://dev-answers.com/solutions/328791e8/how-to-detect-safari-chrome-ie-firefox-and-opera-browser), which still used it in a couple of the checks. Not to mention finding higher version granularity would seem, along with this, more effort than it's worth. Plus I took at the few places we called `userAgent` and it's fine as you said to just stick with it, but maybe wait until it's picked up more, so we're not just doing this for Chrome v90+?

**Comment by martinkuba** [comment]
Ah, by feature detection, I think you meant the places where we have some conditional code based on the browser name. If you can replace that with some feature detection (without looking up the browser name etc.), then yes that would be preferable.

It looks like we only call `userAgent` to detect Firefox version and CriOS. For the Firefox case, you do not need to get the UA, since Chrome has `userAgentData`, so you know it's not Firefox. I don't know if `CriOS` shows up in `userAgentData`, but if `userAgentData` is available at all then it should identify that it's Chrome on iOS (I would think).

In any case, I opened this issue because Chrome is showing a warning, which some users might have questions about. I don't think you need to wait for other browser to implement the new API to address this.

**Comment by patrickhousley** [comment]
Closing. We no longer use `navigator.userAgent` to feature detect for certain browsers and features. The only use of `navigator.userAgent` is for the detection of Electron.
