### ISSUE TITLE
Search filters as URL query string

### ISSUE THREAD

**Issue by victorhugorodrigues** [newrelic/newrelic-browser-agent#1156]
## Summary

Is there a way where I can provide a URL for Traces(distributed-tracing) page with the traceId(or other atributes) to be search as query string directly in the URL?

## Desired Behavior

On the Traces page (distributed-tracing), I can search for the unique "traceId" attribute, and others:
![image](https://github.com/user-attachments/assets/07e20d4b-f262-431d-b933-9cdf4be101ef)

I'm monitoring multiple requests and have the traceId for them, so I would like to create a URL link to new relic directly for that request, and I could use the traceId to mount the URL for it. So it could land on Traces page, already searched for the desired traceId.

For example: https://one.newrelic.com/distributed-tracing?account=3509865&duration=86400000&traceId=07e20d4bf262431db9339cdf4be101ef

I have searched and tried multiple ways, but could not find anything about this, So I'm asking here.

## Additional context

Sorry if this isn't the right repository to ask about this.

**Comment by patrickhousley** [comment]
@victorhugorodrigues Issues raised in this repository are for the browser agent itself. Please use the feedback feature within New Relic, the [New Relic support site](https://support.newrelic.com/s/), or contact your New Relic support rep for issues and suggestions within the New Relic UI.
