### ISSUE TITLE
Safari 15.1: undefined is not an object (evaluating 'this.held.merge')

### ISSUE THREAD

**Issue by plantoeat** [newrelic/newrelic-browser-agent#1174]
I'm seeing multiple errors in Sentry for nr-spa-1.265.0.

- undefined is not an object (evaluating 'this.held.merge')
- undefined is not an object (evaluating 'this.events.held.clear')
- undefined is not an object (evaluating 'u.interactionsToHarvest.held.clear')

https://js-agent.newrelic.com/nr-spa-1.265.0.min.js

## Your Environment

Only seeing errors for Safari 15.1.

**Comment by masatoki-saito** [comment]
I'm in the same situation.

- undefined is not an object (evaluating 'this.events.held.clear')

Only seeing errors for Safari 15

**Comment by cwli24** [comment]
Please note that we will not be fixing this since safari 15.1 falls outs outside our [browser version support](https://docs.newrelic.com/docs/browser/new-relic-browser/getting-started/compatibility-requirements-browser-monitoring/#browser-types) window for recent releases.

**Comment by linearza** [comment]
Seeing a spike in this on our side as well.
