### ISSUE TITLE
Handling of parallel calls to external service time in transaction time as averaged value do not exist

### ISSUE THREAD

**Issue by priyamgoenka1** [newrelic/newrelic-browser-agent#1179]
[NOTE]: # ( ^^ Incorrect latency on the new relic  ^^ )

## Description

Hey,
Facing an issue using new relic for micro-service external call monitoring. What expected is if an external call takes 10ms time and there are 100 concurrent calls in a transaction the latency of a single transaction shouldn't add up this value to increase the final latency on the monitoring by 1s.

Because of this I am unable to get actual latency for my requests and adding alerting on this is quite dicey as concern for me is to raise an issue if the latency is affected, not if the number of batch calls are increasing. Supposing a case where I call external service in loop of go routines.

## Expected Behaviour

It should take an average of all parallel calls to latency so that adding alerts become more accurate

**Comment by metal-messiah** [comment]
Hi @priyamgoenka1 thanks for reaching out.  Can you clarify a little more what outcome you are expecting from the Agent reporting the data?  Is this an issue with aggregating the data in the UI or what data the agent itself sends?  Can you also expand on the concurrent transactions adding up to some value?  The agent itself merely tracks each individual AJAX call as individual AJAX events, so I want to make sure I am following what outcome you are seeking here.

**Comment by priyamgoenka1** [comment]
Yes, the issue is on aggregation of data in the UI side, in the APM metrics we can see the latency of a transaction that includes external calls, web transactions, database calls, custom segments.

**Comment by cwli24** [comment]
@priyamgoenka1 it sounds like this is an APM agent related issue. In which case, we won't be able to address it, as this is the browser agent team (repo). You can follow up with the respective APM agent.
