### ISSUE TITLE
Unable to add Logging Feature to MicroAgent

### ISSUE THREAD

**Issue by matt-calderwood-ep** [newrelic/newrelic-browser-agent#1187]
## Description

After following the guide to include the logging feature here: https://docs.newrelic.com/docs/browser/new-relic-browser/browser-apis/log/ - I am unable to send log events to NewRelic. The code executes but no events are sent from the browser.

If I switch from initialising a `MicroAgent` to an `Agent` instance, everything works as expected.
As the project I am working on is part of a micro-front-end architecture I am keen to use the API driven approach of the `MicroAgent`. Are there any other steps required for activating the feature?

## Steps to Reproduce

Initialise a MicroAgent with the optional Logging feature (as per the post above).
I have repro'd this outside of the MFE architecture of the project I am working on with a simple React + Vite project.

Example Setup Code:
```TypeScript
import { MicroAgent } from "@newrelic/browser-agent/loaders/micro-agent";
import { Logging } from "@newrelic/browser-agent/features/logging";

const newRelicAgent = new MicroAgent({
    init: {
        distributed_tracing: { enabled: true },
        privacy: { cookies_enabled: true },
        ajax: { deny_list: ["bam.nr-data.net"] },
    },
    info: {
        beacon: "bam.nr-data.net",
        errorBeacon: "bam.nr-data.net",
        licenseKey: "...",
        applicationID: "...",
        sa: 1,
    },
    loader_config: {
        accountID: "...",
        trustKey: "...",
        agentID: "...",
        licenseKey: "...",
        applicationID: "...",
    },
    features: [Logging],
});
```

Example Usage:
```TypeScript
newRelicAgent.log("Performance-Event", { level: "INFO", customAttributes: { duration: 1234 }});
```

## Expected Behavior

Log events are sent from the browser and are visible in the New Relic UI.

## Relevant Logs / Console output

Nothing is written to the console. 

## Your Environment

* Browser
Tested with Chrome, Firefox, Safari

* OS
MacOS Sonoma (v14.6.1)

* Browser Agent
v1.265.1

**Comment by metal-messiah** [comment]
Thanks for sharing this @matt-calderwood-ep .  We have work on our backlog to add the logging APIs to the microagent loader, but this work has yet to be done.  I will bring this up with our PM and see if we can prioritize that.

**Comment by metal-messiah** [comment]
Quick update on this from our PM.  We will be adding this functionality to the MicroAgent loader within the next sprint.  Thanks for bringing this forward

**Comment by matt-calderwood-ep** [comment]
Awesome, thank you @metal-messiah 
Really appreciate the fast response and quick turnaround on this.

**Comment by alancoppin** [comment]
Hey @metal-messiah, do you have an ETA about the Logging feature for Micro Agent? I work alongside @matt-calderwood-ep @EducationPerfect. We have a micro-frontend architecture and rely a lot on NR micro-agents for our mfes. That logging feature will be very helpful for our teams 🙌 Cheers!
