### ISSUE TITLE
Getting a tremendous amount of Loading chunk 478 failed out of the new relic JS.

### ISSUE THREAD

**Issue by rylanb** [newrelic/newrelic-browser-agent#1235]
## Description

This seems to have started around Oct 29th or 30th, 2024 in our app.

Getting reported errors in JavaScript: `Unhandled Promise Rejection: Loading chunk 478 failed.` and others that look recursive lik `Unhandled Promise Rejection: Unhandled Promise Rejection: Unhandled Promise Rejection: Unhandled Promise Rejection: Unhandled Promise Rejection: Loading chunk 478 failed.`. We've had over 1000 of these triggered. They don't seem to be affecting users, but I'm not sure it is something I can fix?

Seems to be coming from https://js-agent.newrelic.com/nr-spa-1.270.1.min.js

Related errors I've seen before about this.
https://forum.newrelic.com/s/hubtopic/aAX8W0000008eB3WAI/new-relic-related-error
https://forum.newrelic.com/s/hubtopic/aAX8W0000008eEhWAI/chunkloaderror-issue
https://forum.newrelic.com/s/hubtopic/aAX8W0000015BGUWA2/chunkloaderror-loading-chunk-412-failed

Happy to provide any more details I can about this if it is helpful or close it up if I'm way off.

Thank you!

## Steps to Reproduce

Unfortunately I do not know how to reproduce it as it seems to be happening in Edge and Chrome on Windows. I can provide browser user agents if that is helpful. These are logged in users inside our app triggering this

## Expected Behavior

No JS errors?

## Relevant Logs / Console output

A JavaScriptError occurred in errors#create:

  url: https://<internal url>
name: unhandledrejection
message: Unhandled Promise Rejection: Unhandled Promise Rejection: Unhandled Promise Rejection: Loading chunk 478 failed.
(error: https://js-agent.newrelic.com/nr-spa-1.270.1.min.js)
cause: Unhandled promise rejection
stack: ChunkLoadError

## Your Environment

HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/[130.0.0.0](http://130.0.0.0/) Safari/537.36

HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/[130.0.0.0](http://130.0.0.0/) Safari/537.36 Edg/[130.0.0.0](http://130.0.0.0/)

**Comment by metal-messiah** [comment]
Thanks for reporting this.  We are rolling out a fix in #1234

**Comment by rylanb** [comment]
> Thanks for reporting this. We are rolling out a fix in #1234

Ok great thank you! I should have looked at the PRs !
