### ISSUE TITLE
Explicitly send logs to New Relic from browsers

### ISSUE THREAD

**Issue by t-net** [newrelic/newrelic-browser-agent#125]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )
We have a ReactJS application that is currently sending errors to New Relic. We would like to explicitly send information logs to New Relic as well, so that it is visible in the `Logs` section of New Relic.

## Desired Behavior

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )
Similar to `agent.noticeError`, can the browser agent API have a `agent.noticeInfo` or `agent.log` method that sends information to the `Logs` section of the New Relic dashboard.

**Comment by piyushchauhan2011** [comment]
Looking forward to this feature 🚀

**Comment by CavalcanteLeo** [comment]
is this working? where can I find a doc?

**Comment by piyushchauhan2011** [comment]
I'm also looking for docs, where we can send data to logs instead of proxying it through a custom backend with license key
