### ISSUE TITLE
Data and Attribute Collection for Root Cause of Core Web Vitals

### ISSUE THREAD

**Issue by rr0214** [newrelic/newrelic-browser-agent#131]
**The Problem**

Today we provide customers with CWV data, however that data is not actionable. For example LCP (Largest Contentful Paint) is poor, the customer needs to know which element is causing the poor LCP

**What Are We Going to Do About It?**

Capture data that will help with root cause of CWV. Specifically, capture any missing data from the list below:

- Mobile or Desktop for each CWV metric [we have this already]
- Region associated with each CWV [we have this already]
- Network type, downlink, rtt for LCP and FID. Do we need this for CLS? - Only on natively supported browsers
- Bandwidth for LCP and FID. Do we need this for CLS? - Only on natively supported browsers
- More meaningful element naming for LCP: element type, image url, element id [we have element id already]
- Element size from API for LCP - (width x length) - [already doing this for LCP]  

**Additional Documentation**

[User Story Document](https://docs.google.com/document/d/1KMk2wASBFqtePN7wYLI1yTTPoDJAYfkIVZ1x-eMuXX8/edit?usp=sharing)

<br/>

**Comment by ivankote** [comment]
1
