### ISSUE TITLE
The agent always generates an internal error

### ISSUE THREAD

**Issue by martinkuba** [newrelic/newrelic-browser-agent#134]
## Description

Starting with version 1211, the agent will always generate an internal error:

```
TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at getOrSet (spa:2445)
    at EventContext.<anonymous> (spa:460)
    at Object.emit (spa:2365)
    at safeEmit (spa:2730)
    at nrWrapper (spa:2687)
    at Object.42 (spa:4597)
    at newRequire (spa:32)
    at spa:34
    at Object.10 (spa:951)
```

This does not affect the application the agent is running in, and the error is not displayed in the console either. Rather, it is caught and reported as an internal error. The main impact is that this error is always sent up in the first `jserrors` paylaod.

## Steps to Reproduce

Open any web page with the v1211 version of the agent. Open the network tab in dev tools, and inspect the first call to the `jserrors` endpoint. There will always be an `ierr` bucket in the payload with this error.

**Comment by coreyarnold** [comment]
@metal-messiah is this still an issue?
