### ISSUE TITLE
Including typings file with agent

### ISSUE THREAD

**Issue by metal-messiah** [newrelic/newrelic-browser-agent#136]
## Summary
Include a typings file with the agent for users to use for better IDE experience

**Comment by wrumsby** [comment]
@metal-messiah I know it's not exactly what you're asking for, but are you aware of [`@types/new-relic-browser`](@types/new-relic-browser)?

**Comment by metal-messiah** [comment]
Closing this issue as it is no longer necessary, there is an existing typings file as @wrumsby suggested, it covers most of what would be relevant.  Also, a shift to delivering the agent via NPM would help alleviate this need as well.
