### ISSUE TITLE
Capture supportability metric for ajax requests filtered out by the Deny List

### ISSUE THREAD

**Issue by martinkuba** [newrelic/newrelic-browser-agent#137]
## Summary

This supportability metric would show the total number of ajax requests for which the agent did not generate AjaxRequest events due to rules in the AJAX deny list. This would be useful for troubleshooting missing AjaxRequest events.

**Comment by aubreymasten** [comment]
Adding my suggestions from a duplicate ticket: The agent should distinguish between internal requests (requests made to nr-data.net) and requests blocked on customer-specified domains, either by recording only the number of requests to customer-specified domains or with two separate metrics.

**Comment by metal-messiah** [comment]
This work has been completed.
