### ISSUE TITLE
CWV - capture network information for LCP and FID

### ISSUE THREAD

**Issue by martinkuba** [newrelic/newrelic-browser-agent#144]
## Summary
Add the following as attributes on the PageViewTiming event for LCP and FI

* [network type](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/type)
* [rtt](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/rtt)
* [downlink](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/downlink)

Attribute names: networkType, networkRtt, networkDownlink 

If a browser does not support the Network Information API, then these attributes should not be added on the event.

The consumer needs to be updated to prefer these attributes over custom attributes.

**Comment by metal-messiah** [comment]
This work has been completed
