### ISSUE TITLE
CWV - element identifying attributes for LCP

### ISSUE THREAD

**Issue by martinkuba** [newrelic/newrelic-browser-agent#145]
## Summary

Add attributes to PageViewTiming event for LCP
* [element type](https://developer.mozilla.org/en-US/docs/Web/API/LargestContentfulPaint/element)
* [image url](https://developer.mozilla.org/en-US/docs/Web/API/LargestContentfulPaint/url) (if the element is an image)

Attribute names: elementType, imageUrl

If a browser does not support the Network Information API, then these attributes should not be added on the event.

The consumer needs to be updated to prefer these attributes over custom attributes.

**Comment by coreyarnold** [comment]
@metal-messiah @cwli24 looks like this was already completed. Can one of you check on that and close if it's done?
