### ISSUE TITLE
Browser agent causing lower Lighthouse score

### ISSUE THREAD

**Issue by rr0214** [newrelic/newrelic-browser-agent#151]
The customer is experiencing a lower Lighthouse Best Practice score because of the Browser agent v1210 use of deprecated "unload" event. They would like this fixed in a future release to improve their Lighthouse rating.

**Comment by aubreymasten** [comment]
We are tracking this issue as part of a larger effort to allow pages with the Browser agent installed to enter the BFCache.

**Comment by darkmasta** [comment]
New Relic isn't just causing lower performance score but lowering scores in Best Practices category too.

**Comment by meddlesome** [comment]
Has v1220 solved this problem? https://github.com/newrelic/newrelic-browser-agent/releases/tag/v1220
