### ISSUE TITLE
Add sessionTraceId to agent event harvest payload bodies

### ISSUE THREAD

**Issue by metal-messiah** [newrelic/newrelic-browser-agent#153]
## Summary

If we obtain a session trace id from the sampling decision, we should append it to each event harvest payload.  It should be appended as a property in the body named `sessionTraceId` {[key: string]: string}

## Desired Behavior

All events sent to the consumer should have a `sessionTraceId` property in the body if present.

**Comment by aubreymasten** [comment]
Shipped in [Browser agent v1214](https://docs.newrelic.com/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1214#added-session-trace-ids-to-harvests)
