### ISSUE TITLE
Agent payloads over 1MB in size are rejected

### ISSUE THREAD

**Issue by martinkuba** [newrelic/newrelic-browser-agent#155]
## Description

The New Relic Browser ingest will reject (HTTP 413) payloads that are larger than 1MB. This can be problematic for session traces payloads (/resources endpoint) and page actions (/ins endpoint). 

## Steps to Reproduce

Add a large number of page actions using the addPageAction API. Wait until the the agent makes a call to the /ins endpoint (30 seconds after navigation start).

## Expected Behavior

Session traces are likely to send the most amount of data. However, session traces are heavily sampled, so the impact is very small. The agent could either split the payload into multiple smaller calls or drop the excess data.

The size of the page action payload is entirely given by the user of the addPageAction API - by the number of events and number/size of attributes. These payloads could also be split into multiple smaller payloads or dropped. The impact is bigger because page actions are not sampled (they will be sent from every page view). The behavior could also be controlled by the application owner through a configuration or API.

**Comment by coreyarnold** [comment]
We should track down information on how much this is occurring. Number of 413 responses, distribution of current payload sizes received,...
