### ISSUE TITLE
LCP should not be reported when page is opened and loaded in background

### ISSUE THREAD

**Issue by ixjamesyoo** [newrelic/newrelic-browser-agent#170]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )
The NewRelic agent reports LCP times for pages that are opened and loaded as a background tab (i.e. the `document.visibilityState` is initially `hidden` and remains as such until user focuses the tab). This is different from the web-vitals library which does not report an LCP when the page is hidden since navigation start.

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
See video here for details: https://youtu.be/0gH6NeJqLZw

**tl;dr** Open page as background tab. Wait for approx 30 seconds (or however long). Make page visible. See inflated effects on LCP times reported by NR browser agent

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )
Pages that are initially opened and loaded in the background should not report their LCP

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )
See video for context

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* Chrome  96.0.4664.93

## Additional context

[TIP]:  # ( Add any other context about the problem here. )
https://github.com/GoogleChrome/web-vitals/blob/main/src/lib/getVisibilityWatcher.ts
note that `firstHiddenTime` is assigned a value at initialization to account for the scenario reported above.

**Comment by ixjamesyoo** [comment]
Code snippets for the console.logs generated in the video:

- simple PerformanceObserver

```
 <script>
      try {
        let lcp;

        const po = new PerformanceObserver(entryList => {
          const entries = entryList.getEntries();
          const lastEntry = entries[entries.length - 1];

          // Update `lcp` to the latest value, using `renderTime` if it's available,
          // otherwise using `loadTime`. (Note: `renderTime` may not be available on
          // image elements loaded cross-origin without the `Timing-Allow-Origin` header.)
          lcp = lastEntry.renderTime || lastEntry.loadTime;
          console.log(
            'performance observer LCP:',
            lastEntry.renderTime ? lastEntry : lastEntry.loadTime,
          );
        });

        po.observe({ type: 'largest-contentful-paint', buffered: true });
      } catch (e) {
        // Do nothing if the browser doesn't support this API.
      }
    </script>
```

- web-vitals script
```
<script type="module">
      import { getLCP } from 'https://unpkg.com/web-vitals?module';

      getLCP(foo => console.log('web vitals - LCP timing', foo));
    </script>
```

- NR observer - `loader/timings.js`
```
function lcpObserver(list, observer) {
  var entries = list.getEntries();
  if (entries.length > 0) {
    var entry = entries[entries.length - 1];

    if (pageHiddenTime && pageHiddenTime < entry.startTime) {
      console.log("NR LCP Observer - short circuit LCP");
      return;
    }

    var payload = [entry];

    var attributes = addConnectionAttributes({});
    if (attributes) payload.push(attributes);

    console.log("NR LCP Observer - handling lcp payload", payload);
    handle("lcp", payload);
  }
}
```

**Comment by cwli24** [comment]
Should be noted as well that we're planning to transition to directly using Google's CWV library soon.
