### ISSUE TITLE
Micro Front Ends -- Agent can report Global and Local Errors

### ISSUE THREAD

**Issue by metal-messiah** [newrelic/newrelic-browser-agent#180]
## Outcomes

- [ ] Traditional Agent builds can report errors as they do now
- [ ] Modular agent builds can report global errors, if not disabled
- [ ] Modular agent builds can report local errors, if enabled
- [ ] Any error reported by the agent will be harvested and sent to the configurations defined in the agent configuration object
- [ ] API access should be standardized across all build types of the agent

**Comment by MartijnKooij** [comment]
Is there any progress on these MFE topics? I think this is what we are waiting for: The ability for MFE components, hosted in a shell application that ALSO reports to NewRelic, to report their own metrics and events to their own application. Right now any and all metrics are "intercepted" by the hosting application and collected in their NewRelic application.

**Comment by jmezach** [comment]
I was wondering the same things actually. It looks like there is some initial work done and available [here](https://www.npmjs.com/package/@newrelic/browser-agent), but the feature set is fairly limited by the looks of it. Is this still being worked on?

**Comment by metal-messiah** [comment]
@MartijnKooij @jmezach Following up on this, thank you for your continued interest. Work on this topic was shelved for some time, but ha nows been prioritized, and is on our board to be completed by next quarter. This will likely include NPM  agent loaders that mirror what is available via New Relic's UI, APM and copy/paste, a custom agent loader that can be configured for custom features as plugins, as well as an initial MFE loader that supports page actions, metrics, and error capturing.
