### ISSUE TITLE
AJAX Deny List Case Sensitivity

### ISSUE THREAD

**Issue by metal-messiah** [newrelic/newrelic-browser-agent#188]
## Summary
The AJAX Deny List is case sensitive.  This is not expressed to the customer anywhere, and did cause some confusion for a customer and a GTSE.  See screenshot below

<img width="909" alt="Screen Shot 2022-03-01 at 9 41 58 AM" src="https://user-images.githubusercontent.com/24296585/156220749-061f0619-6c60-4b82-80f4-a76186787796.png">

## Possible Solution
Some options:
* Put language into the UI help text, indicating these URL rules are case sensitive.
* Make the AJAX Deny List case insensitive

**Comment by aubreymasten** [comment]
This may be a task for the UI team to update settings page and documentation.
