### ISSUE TITLE
Angular: Route Changes to lazy-loaded modules are not captured on first navigation

### ISSUE THREAD

**Issue by aubreymasten** [newrelic/newrelic-browser-agent#192]
When the Browser agent is installed on a page with an Angular app using lazy-loaded routing, the first route change to a lazy-loaded route will not be captured.

## Steps to Reproduce

Using `nr-angular-lazy-loading` application below:
* Update Browser agent config values using [README instructions](https://github.com/newrelic/newrelic-browser-agent#set-application-id-and-license-key) in `/src/index.html`
* Run`npm install`
* Run `ng serve`
* Visit `localhost:4200`
* Click `Lazy` then `Eager` then `Lazy`, then query for BrowserInteractions created.
 *  Without any fix implemented, you should see 3 BrowserInteractions events (initialPageLoad, Eager, Lazy), with the first `Lazy` interaction missing. 

## Additional context
Replication app: [nr-angular-lazy-loading.zip](https://github.com/newrelic/newrelic-browser-agent/files/8429911/nr-angular-lazy-loading.zip)

**Comment by patrickhousley** [comment]
Closing. SPA route changes with lazy loaded chunks and/or XHR calls should be resolved with the merging of the below PRs.

#311 
#314 
#315
