### ISSUE TITLE
Audit methods for reporting port value across features

### ISSUE THREAD

**Issue by aubreymasten** [newrelic/newrelic-browser-agent#195]
## Summary

To support links between Browser data types in the UI (ex: Session Traces <-> Ajax <-> Spans), we should ensure the `port` value reported by the agent on all pageUrl and requestUrl resources is consistent. 

## Desired Behavior

If specified, the agent should report the port value of all network requests and page URLs.
For requests where port is not specified:
```
fetch('http://example.com')
```
we do not need to assume port as long as the protocol of the request is captured, from protocol the backend can infer default port (https: 443, http: 80).

**Comment by coreyarnold** [comment]
Closing this as it was moved over to Jira.
