### ISSUE TITLE
Illegal Invocation Intermittent error on Windows

### ISSUE THREAD

**Issue by dvnrsn** [newrelic/newrelic-browser-agent#262]
## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

Using New Relic's APM, we are experiencing intermittent errors in the hundreds surfaced in Sentry as of the last 2 months.

```
TypeError

Illegal invocation
```

## Steps to Reproduce

It is intermittent but always specific to Windows 10 Chrome and initial page loads.

## Expected Behavior

No error

## Relevant Logs / Console output

<img width="654" alt="image" src="https://user-images.githubusercontent.com/9112811/184699862-6890a872-b8db-4aed-bfda-379788e44249.png">

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

* NR Python Agent
* APM Lite
* Chrome
* Windows 10

## Additional context

Similar conversations: 
* https://discuss.newrelic.com/t/illegal-invocation/148978
* https://discuss.newrelic.com/t/uncaught-typeerror-illegal-invocation-error-thrown-in-js-agent-newrelic-com/154260

**Comment by ionTea** [comment]
+1 
Same for me, I see a lot of these for users on Chrome on Windows 10

**Comment by coreyarnold** [comment]
Thanks for the bug report @dvnrsn and the confirmation @ionTea . I'll work with the team to see if we can reliably reproduce the issue and get to the bottom of it.
