### ISSUE TITLE
Browser agent injected from the php APM extension is not working anymore

### ISSUE THREAD

**Issue by ilario-pierbattista** [newrelic/newrelic-browser-agent#273]
## Description

I have the browser agent injected automatically in the HTML by the newrelic PHP extension (`newrelic.browser_monitoring.auto_instrument=1`).
Starting from the night of 2022-08-31, the browser agent fails to load with the following error in the browser console.

```
index:5 Uncaught (in promise) Error: Missing Configuration -- New Relic Browser agent requires applicationID, errorBeacon, beacon, licenseKey
    at index:5:68039
    at new Promise (<anonymous>)
    at index:5:66044
    at index:5:68344
    at index:5:68349
    at index:5:185
    at index:5:189
```

## Steps to Reproduce

Let it inject automatically by APM.

## Expected Behavior

The browser agent works correctly.

## Relevant Logs / Console output

The necessary secrets (applicationID, errorBeacon, beacon, licenseKey) are also injected automatically. They are in the page, but the agent fails anyway.

## Your Environment

- NR PHP Agent 10.0.0.312 (upgraded yesterday after the first failures, 9.17.1.301 before).
- Chrome
- Ubuntu 20.04

## Additional context

If I copy the content of the script tag that loads the agent into the browser console to run it, then the agent correctly starts.
I see it loads the agent's latest version (v1218).

Also, I see that the APM-injected version changed to v1218 on the same day. 
https://docs.newrelic.com/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1218/

**Comment by coreyarnold** [comment]
Thanks for the bug report @ilario-pierbattista . We're actively looking at why this occurs for you and hope to track it down quickly. Can you share some details about your setup? How are your secrets included in page when auto injected? Do they show up before or after the agent script?

**Comment by ilario-pierbattista** [comment]
The secrets are injected as well by the PHP extension. It places them at the end of the body tag. The snippet is placed as the first script in the head tag.

Today it magically works again. But I see that the snippet loads the v1216 version of the browser agent.

What kind of detail might you need to know?

**Comment by coreyarnold** [comment]
This is great. Yeah, we rolled back to the previous version while we investigate and put a fix in place. Thanks!

**Comment by metal-messiah** [comment]
We have raised a PR for addressing this --> https://github.com/newrelic/newrelic-browser-agent/pull/274

This should be reviewed and hopefully deployed with our latest changes by EoD, and we will follow up with you to ensure that nothing else has affected your implementation of the Browser Agent as we roll out

**Comment by coreyarnold** [comment]
We will leave this bug report open until we roll out the next version of the agent with this fix and have you validate things are working as expected @ilario-pierbattista

**Comment by patrickhousley** [comment]
Hi @ilario-pierbattista can you confirm this issue is resolved?

**Comment by ilario-pierbattista** [comment]
Hi @patrickhousley sorry I forgot to give feedback. Yes I confirm it's solved.
Thank you

**Comment by patrickhousley** [comment]
Thanks for the confirmation @ilario-pierbattista
