### ISSUE TITLE
Expose modules, so a user could create own version of `agent-loader`

### ISSUE THREAD

**Issue by o-alexandrov** [newrelic/newrelic-browser-agent#292]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

Developers are unable to create own agent-loader (ex. `cdn/agent-loader/spa.js`), combining modules you already have in this repo.

Current problem could be summarized as:
- project A uses only 1 feature from `lite` and 1 feature from `pro`
- project A will always import all features no matter what's actually used because a loader checks `enabledFeatures` dynamically

## Desired Behavior

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

A user-developer could create own version of `agent-loader` (ex. `cdn/agent-loader/spa.js`).

## Possible Solution

You already expose all features from `@newrelic/browser-agent-core`.
What you don't expose are:
- `configure`
- `stageAggregator`

Note: `agentIdentifier` could be exported, but most projects already have a unique ID generator.

The solution to this issue is extremely simple. Just export the above API (2 functions).

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

There are many reasons (all come from inefficiency).

**Comment by o-alexandrov** [comment]
Btw, loading a loader from your CDN is error-prone, as ad blockering browser extensions block loading of:
- `https://js-agent.newrelic.com/nr-loader-spa-current.min.js`

**Comment by o-alexandrov** [comment]
The loader from CDN, all NewRelic's endpoints are all error-prone to the [Ad Blockers issue was reported ~5 years ago and still exists.](https://discuss.newrelic.com/t/new-relic-browser-is-blocked-by-adblock/49937/10)

By letting your users to create own loaders, you could help users to have a necessity to only proxy the requests, while not being required to host unnecessarily bloated version of a NewRelic loader

**Comment by metal-messiah** [comment]
Thanks for suggesting this.  This is a topic we have been actively probing interest in and will go a long way toward our ability to prioritize this capability.  There are some obstacles still in place that would need to be addressed before this makes sense from a public user perspective, as certain features are unfortunately still interdependent.  I will make sure our Product Manager is aware of the interest in this topic to aid in our planning efforts.

**Comment by JohnnyBravoFromTexas** [comment]
Giving users the ability to pick and choose features providing a custom version of our agent is on our roadmap.  I will review the above suggestion with the team.  Thanks for sharing your feedback.

**Comment by metal-messiah** [comment]
Hi OP,
if you are still interested in stitching together a loader from feature modules, we have an NPM entry point in prerelease right now (@newrelic/browser-agent) that allows for this behavior. It is set to come of out prerelease some time this quarter. Would love feedback on that if you end up implementing. 

Closing this issue.
