### ISSUE TITLE
Dashboard still serving old release

### ISSUE THREAD

**Issue by ben-reitz** [newrelic/newrelic-browser-agent#295]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

Hi,

Our dashboard is still serving version `1216` rather than the latest `1220`. Is this expected behaviour? If so, is there any timeline as to when the new version will be served in the dashboard?

## Steps to Reproduce

Using the copy-and-paste installation method, served the older version of the browser agent.

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )
Expected version 1220 to be provided

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by coreyarnold** [comment]
Good day @ben-reitz ! We cut the v1220 release and are working on deploying it to production. We will update the [release notes](https://docs.newrelic.com/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1220/) with the appropriate dates when we complete that release.

**Comment by ben-reitz** [comment]
@coreyarnold Ah right so it is the current expected behaviour! Thanks for letting me know 😄  Really looking forward to the release and getting rid of the 3rd party cookies!

**Comment by ben-reitz** [comment]
@coreyarnold It looks like you're generally modernising it with the removal outdated code, old polyfills and script insertion. We've been holding off on adding this to our application solely because of the cookies and the difficulties that come with managing that in the EU so it'll be brilliant once we get some real observability of our browser app!

**Comment by coreyarnold** [comment]
Love it and looking forward to helping you gain some observability!! 🎉

**Comment by ben-reitz** [comment]
@coreyarnold Hey Corey! Do you happen to have any updates on the release? The release page says "Estimated around 12/13/2022" but it looks like the old version is still the only one available.
