### ISSUE TITLE
Browser agent: `unhandledrejection` reason is not always of type a string

### ISSUE THREAD

**Issue by atma** [newrelic/newrelic-browser-agent#349]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

After the release [v1220](https://docs.newrelic.com/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1220/) of New Relic's browser agent we are seeing many of captured errors with the message `[Object object]` and no additional information
<img width="535" alt="image" src="https://user-images.githubusercontent.com/72800/208003125-6a1b8055-f92d-49d6-ac49-941228fdc159.png">

By reviewing a changelog we have found that [the next](https://docs.newrelic.com/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1220/#capture-unhandled-promise-rejections) feature were introduced 
> **Capture unhandled Promise rejections**
> The Agent now observes and captures unhandled Promise rejections as JavaScript Error objects.

Also by looking the source code we've found that the agent is always expect the rejection reason always is the type of string, if not `.toString()` will cast it to string anyway:
https://github.com/newrelic/newrelic-browser-agent/blob/b6b96f62fa7c127e5e9c5e79e0a401b509aa921a/packages/browser-agent-core/src/features/jserrors/instrument/index.js#L63-L64
 
But its type is not strictly defined. Also as [MDN says](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/reject#description) 
> For debugging purposes and selective error catching, it is useful to make reason an instanceof Error.

In this case in `const err = new Error(`${e.reason}`)` the type of `e.reason` will be an `Error`, an so on.

Is it possible to add some logic here to see human readable messages?

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

Add a listener
```js
window.addEventListener('unhandledrejection', (e) => {
  const err = new Error(`${e.reason}`)
  console.log(err)
})
```

And instantiate some unhandled promise

```js
(new Promise((res, rej) => rej({a: 1})))
```
<img width="386" alt="image" src="https://user-images.githubusercontent.com/72800/208005506-1c2f70c8-2728-4a63-adea-2b67905641ad.png">

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

```
> Error: {"a":1}
> Error: reason

```

[NOTE] ## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

Occurs in any browser where v1220 agent is loaded and a page has unhandled promises with non-string reasons.

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by bjfield** [comment]
@atma : Thanks for contributing and for the detailed description. The team is taking a look and planning to address the issue in an upcoming release.

**Comment by metal-messiah** [comment]
Closing after merging PR to main.  Expected to ship in v1224
