### ISSUE TITLE
Offer “Ajax” feature in npm package

### ISSUE THREAD

**Issue by eelco** [newrelic/newrelic-browser-agent#356]
I very much like the approach of this agent and the ability to opt in to very specific features. I’m curious if there is any planning / ETA that can be shared for the Ajax feature to be enabled? I see that most of the code is there, but it’s not included in the available features.

**Comment by metal-messiah** [comment]
Hi, thanks for contributing here!

Would you mind pointing me to what you are referring to?  The main agent build that is installable through the New Relic UI, both copy/paste and APM injection includes the AJAX feature enabled out of the box. 

Is this question in reference to NPM specifically?

**Comment by eelco** [comment]
Hey, thanks for the quick response! Yes, this refers to the NPM version specifically, because the APM version is not applicable for our setup and the Copy/Paste version is doing too much for our needs (its instrumentation has undesired side effects).

**Comment by yusomalo77** [comment]
Hi! Is there an update on this issue?
