### ISSUE TITLE
deny-list.js throws "Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by norman-ags** [newrelic/newrelic-browser-agent#377]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Hi! We noticed that there's a new version released yesterday, v1222. Our app had an issue earlier today where the user attempts to upload a file, clicks save, and then it throws an error (see relevant logs)

We have a workaround and switch to the lite version for now 
![image](https://user-images.githubusercontent.com/63862061/213608138-79bd4e43-2b96-4aa6-9a58-2a073f8b5a4a.png)

## Expected Behavior

1. Newrelic shouldn't cause an app feature to not work, even if there's an error on the newrelic's JS file.
2. It shouldn't throw an error `deny-list.js throws "Cannot read properties of undefined (reading 'length')`

## Relevant Logs / Console output

![image](https://user-images.githubusercontent.com/63862061/213607922-18aa13a8-b417-4e50-a943-7dc26289ac00.png)

## Additional context

**Comment by cwli24** [comment]
@norman-ags Hi, thanks for the report! Do you happen to have a live site exhibiting this behavior? We have a suspect of the source but want to verify. That or the page source corresponding to the error stack trace line:column.

**Comment by patrickhousley** [comment]
Morning @norman-ags and thanks for reporting this issue. We would like to investigate the issue but need additional information. Could you please provide a reproduction of the issue?

**Comment by norman-ags** [comment]
Hi. Sorry I was on vacation. We don't have the page source anymore, but the error happened [here](https://github.com/newrelic/newrelic-browser-agent/blob/main/src/common/deny-list/deny-list.js#L80)

**Comment by cwli24** [comment]
@norman-ags But is that still happening? Line 17-19 in that file should've addressed this issue wherein the `domain` or `params.hostname` is potentially undefined.

**Comment by norman-ags** [comment]
It did happen on v1222. Will check on the new ones and will come back here. Thanks!

**Comment by norman-ags** [comment]
Hi! This is fixed and the version loaded when we tested is v1223. I'll close this issue now, thanks!
