### ISSUE TITLE
3rd party cookies still being set in v1222

### ISSUE THREAD

**Issue by ben-reitz** [newrelic/newrelic-browser-agent#394]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Hi, I'm using v1222 and a lot of 3rd party cookies are still being set by New Relic in the browser:

<img width="616" alt="Screenshot 2023-02-03 at 08 46 54" src="https://user-images.githubusercontent.com/20502986/216554134-75be5c08-6147-4d8d-bc85-4ad0a9f68b5e.png">

I thought this was something that was removed in v1220 according to [the release notes](https://docs.newrelic.com/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1220/)?

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account 
or API keys! )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )
Expected no 3rd party cookies to be set

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

Latest chrome desktop

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by patrickhousley** [comment]
Morning @ben-reitz and thanks for reporting this issue. Is it possible that you visited the NR1 UI https://one.newrelic.com/nr1-core in that same browser? Our UI platform still uses cookies but the browser agent itself no longer uses cookies. Could you try clearing your browser cookies and visiting your instrumented site again? If you still see cookies being set by the agent, can I get the address to the instrumented site?

**Comment by ben-reitz** [comment]
@patrickhousley Yep - you're right of course! So sorry for wasting your time. Just tried it in an incognito window and there are no cookies being set 👍🏼

**Comment by patrickhousley** [comment]
Thanks @ben-reitz for verifying for me. No waste, always happy to talk to our customers! Have a great day.
