### ISSUE TITLE
Abort cleanup under adblocking can cause unexpected global object changes

### ISSUE THREAD

**Issue by djimenez** [newrelic/newrelic-browser-agent#418]
## Description

in commit https://github.com/newrelic/newrelic-browser-agent/commit/4e40a5a8528fc4642739be0f86bf631bc35a5678 new abort handler that cleans up all wrapped objects was added (I believe was first released in v1225). This can be triggered if a client has any type of adblocking or filtering web proxy. 

The problem is that new relic agents like the one for .net will auto-instrument the browser agent first on a page. This means new relic browser agent is the first to wrap things like Promise. Other libraries used on the page then may ALSO try to wrap Promise / fetch / etc.  If the abort clean up behavior gets triggered after these libraries have executed, which is likely because it happens after network request attempts, new relic browser agent will unwrap any objects its touched, usually reverting to the original browser versions and eliminating any wrapping other libraries performed.

## Steps to Reproduce

1. use an auto-instrumenting agent or copy / paste where the new relic browser agent is loaded first on a page.
2. use a library or code that also touches one of the same object new relic browser agent does. Note: this may be fully wrapping like new relic does, or could just be attachment of "extension" functions to the NR WrappedPromise object. 
3. load the page while using an adblocker, or use something like chrome devtools to block requests to js-agent.newrelic.com

## Expected Behavior

new relic browser agent should not destroy modification to global objects that may have been touched since it loaded.

Since it may be tricky for the clean up code to tell if something else has modified the same objects, I would suggest just removing the clean up code.

## Relevant Logs / Console output

as a hacky way to track what was happening, in chrome, I set a breakpoint at the first line of the NR browser agent loader. While in the breakpoint I put this in the js console so I could log when and who was overwriting the global object of interest, Promise in this case:

```
window._Promise = window.Promise; window.__defineSetter__("Promise", (v) => { this._Promise = v; console.trace(v); }); window.__defineGetter__("Promise", () => { return this._Promise });
```

I then unpaused the debugger and examined the console log to see Promise being wrapped twice, but then reverted to the browser's native function.

## Your Environment

Should be any browser where you can trigger the abort behavior. We were specifically using the spa loader.

**Comment by metal-messiah** [comment]
Thanks for reporting this @djimenez !  We have had similar reports come in and have prioritized this issue for our next release.  You can check out the PR [here](https://github.com/newrelic/newrelic-browser-agent/pull/417) if you are interested in the progress. 

Thanks again,
