### ISSUE TITLE
Googlebot indexes agent relative paths

### ISSUE THREAD

**Issue by macdar** [newrelic/newrelic-browser-agent#419]
I see a lot of invalid URLs indexed by Googlebot for months, but it is getting worse since 4 February 2023. I have noticed you released a bugfix for that in v1225 and it was about 2 weeks ago. It seems to be related.

## Description

I see a lot of agents relative paths indexed by Googlebot, for example:

- https://example.com/p/103066/jserrors/aggregate
- https://example.com/p/139312/page_view_event/aggregate
- https://example.com/p/186304/metrics/aggregate
- https://example.com/p/56019/metrics/aggregate
- https://example.com/p/195341/ajax/aggregate
- https://example.com/p/129952/spa/aggregate

for comparison, a valid URL on my website looks like https://example.com/p/103066/url-slug

## Steps to Reproduce

I can't give steps, unfortunately. I see these invalid URLs in [Google Search Console](https://search.google.com/search-console/about).

## Expected Behavior

Googlebot doesn't index agent relative paths.

## Additional context

> [v1225](https://github.com/newrelic/newrelic-browser-agent/releases/tag/v1225)
> Resolve Google indexing of agent relative paths
> In previous versions, the agent script included relative paths to its lazy-loaded chunks, which Googlebot picked up and attempted to index as pages. This change removes those relatives paths from the loader and centralizes our lazy chunk loading of agent features.

**Comment by patrickhousley** [comment]
Thanks for reporting this issue @macdar . Can you confirm that 1225 fixes this issue?

**Comment by macdar** [comment]
@patrickhousley I think it doesn't fix that. It is even worse. Please have a look at the following screenshot from Google Console:
![IMG_2232](https://user-images.githubusercontent.com/284649/221208304-2d6b7c13-8855-4d6a-83e9-21e949510f31.jpeg)

**Comment by macdar** [comment]
@patrickhousley https://forum.newrelic.com/s/hubtopic/aAX8W0000008emPWAQ/googlebot-indexes-browser-agent-relative-paths

**Comment by patrickhousley** [comment]
@macdar can you verify your site is using version 1225 of the agent? There is a `v` query parameter in all the network calls the agent makes.

**Comment by macdar** [comment]
I saw v1225 when the browser plugin was enabled.

**Comment by patrickhousley** [comment]
Version 1225 does not include any relative URLs. With the agent disabled, I assume that the google search dashboard is no longer showing those agent URLs. Can you re-enable the agent and check again?

**Comment by patrickhousley** [comment]
@macdar Are your still seeing this issue in your site? If so, is your site public facing and something you can provide a link for?

**Comment by macdar** [comment]
@patrickhousley thank you for your engagement. I will re-enable the agent and give you the link on Monday. We want to investigate Google Console for some time after disabling the plugin. Maybe Google Console has some delay.

**Comment by macdar** [comment]
@patrickhousley 
![image](https://user-images.githubusercontent.com/284649/223923942-445e348f-2c17-401e-9031-a77907f910fb.png)
