### ISSUE TITLE
Performance issue with v1.230.0 addConsoleSupportabilityMetrics with redux-logger and large redux state

### ISSUE THREAD

**Issue by lnicho** [newrelic/newrelic-browser-agent#467]
## Description

We provide a B2B interactive data visualization app, and use New Relic for tracking general metrics, as well as specific Page Actions during use. I was diagnosing a performance issue that popped up today, and I think I've tracked it down to the `stringify` function that was updated with the latest release today. Below is a screenshot of a keypress that triggers a change in one of our visualizations that loads a bunch of data:

![Screenshot 2023-04-13 at 10 59 59 PM](https://user-images.githubusercontent.com/3784447/231939778-755bc2c2-cb94-4e7f-8a14-cbade0cdf0b7.png)

Before today there was nominal overhead from New Relic, but now the `o` function (which is the uglified/minified stringify code below) appears to be adding >6s of overhead to the event:

```
            function o(e) {
                try {
                    return JSON.stringify(e, i())
                } catch (e) {
                    try {
                        n.ee.emit("internal-error", [e])
                    } catch (e) {}
                }
            }
```

I believe it's related to the following change in today's release: https://github.com/newrelic/newrelic-browser-agent/commit/8e0b1584900c3465f12651330865b3ee8af2ab7b#diff-4774827dea3c59518cba8b975acb17892dc67e6e8dabd6754e73b368e5ea1fd5R34

Some factors that may contribute from our end:
- Our redux state is quite large, due to the nature of our application (data visualization)
- We're also running the following monitoring libraries in conjunction with New Relic:
  - Heap (will be removed soon)
  - LogRocket

Please let me know if there is additional information I can provide.

---

**Update**: It does relate to our large redux state, and the added `addConsoleSupportabilityMetrics` interacting with redux-logger. 

## Steps to Reproduce

1. have a redux state with a large amount of structured data (~4MB should be enough to demonstrate).
2. enable redux-logger
3. trigger an action to have redux-logger log the current/new states
4. observe a ~40ms overhead of `addConsoleSupportabilityMetrics` when measuring the size of the console logs

## Expected Behavior

`addConsoleSupportabilityMetrics` should not produce meaningful performance overhead

## Your Environment

Client:
Chrome 112.0.5615.49 on macOS

Application:
React/Redux webapp
- redux-sagas
- d3
- apollo-client

NodeJS API

The New Relic agent is deployed using the APM deployment model (APM is installed on our backend, and serves nr.js to the frontend)

**Comment by lnicho** [comment]
I don't know for certain that our application state is being stringified, but I listed it as a factor that may contribute to the decreased performance.

I don't have enough knowledge about the NR javascript agent to do my own RCA and create a reproduction sample, but I do have the agent still enabled in one of our dev environments, and I'm happy to do a shared debugging session to help track down the root cause.

What I do know is:
- The affected environments did not have any code changes deployed by us since March 13th
- I noticed the degraded performance yesterday afternoon but not yesterday morning, which aligns with the NR agent release
- Chrome dev tools identify the NR stringify function as being 96% of the app runtime, which was also updated in yesterday's agent release

**Comment by lnicho** [comment]
I will give it a go and let you know. Thanks!

**Comment by lnicho** [comment]
<img width="2049" alt="Screenshot 2023-04-14 at 1 05 23 PM" src="https://user-images.githubusercontent.com/3784447/232123301-36aa52f1-13e9-462d-92fb-f4964d1ad90d.png">

Here it is running with the non-minified script. Sorry I didn't make that more clear, the `o` function in my first screenshot is `stringify` in this one.

**Comment by patrickhousley** [comment]
Now that you are loading the unminified code, you can modify that to say console.log out places where stringify are called to see what feature of the agent is calling stringify so much and what it is actually passing to stringify.

**Comment by patrickhousley** [comment]
Hi @lnicho where you able to trace the calls to `stringify` and determine where the function is being called from and what is being passed to it?

**Comment by lnicho** [comment]
Hi! I've been out this weekend and am just getting around to this. Adding some logging shows that it's `addConsoleSupportabilityMetrics`, and what's likely an interaction with redux-logger:

<img width="753" alt="Screenshot 2023-04-17 at 11 58 35 AM" src="https://user-images.githubusercontent.com/3784447/232558197-3a0daab6-d05d-42b8-ae51-805af63d1154.png">

Looking at what it's stringifying, it is the redux state which is quite large in our case.

**Comment by lnicho** [comment]
I'm realizing that `addConsoleSupportabilityMetrics` was introduced in 1.230 as well: https://github.com/newrelic/newrelic-browser-agent/commit/0cbabf8b9c9ee9ef16386521bf8827a2b5b2911e#diff-8039368d1bd44becc9b29e601ea884bbf73b86ecabecfe8a50f03608a69a7832R20

It just happens to be its call to stringify that's causing us pain.

**Comment by patrickhousley** [comment]
Yea, can you try 1.229 and see if you still have the same performance issues?
https://js-agent.newrelic.com/nr-loader-spa-1.229.0.js

**Comment by patrickhousley** [comment]
Ok thanks. That makes sense. I will take this back to the team.

The console supportability metrics were a precursor to us adding log capturing to the agent. This uncovers something we need to be careful about and that is how much of the parameters passed to console log get serialized and sent in the agent payload.

**Comment by lnicho** [comment]
Awesome, thanks! I went ahead and updated the issue as well so it's easier to understand. We went ahead and disabled redux-logger in production so we can re-enable the agent, and we can deal with the performance issues in our dev environment or disable the agent there until it's resolved.

Thanks again for helping me get diagnostics out of the agent, and let me know if there's anything else I can provide from my end.

**Comment by patrickhousley** [comment]
Thanks @lnicho . I am going to leave this open while we look at what to do with the supportability metrics. Any input you or anyone else might have on capturing logs in the agent would be welcome.

**Comment by patrickhousley** [comment]
@lnicho could you take a look at #482 and see if that resolves the performance issues you were seeing?

**Comment by patrickhousley** [comment]
@lnicho the test build of that PR is available at https://js-agent.newrelic.com/test/nr-loader-spa-1.230.0.js

**Comment by lnicho** [comment]
@patrickhousley thanks for providing the test build. The update helps, but doesn't solve the issue:

<img width="2054" alt="Screenshot 2023-04-24 at 2 39 37 PM" src="https://user-images.githubusercontent.com/3784447/234100080-856aad64-7821-44da-8d00-34fe6d9ca0bc.png">

This is the same event with stringify vs approximateSize. By adding logs to the script I can see that with stringify it adds ~40ms every time it logs the redux state (twice per action, since redux-logger logs the previous and next state). With approximateSize this drops to ~30ms every time it logs the redux state.

**Comment by patrickhousley** [comment]
Thanks @lnicho. When the `approximateSize` method returns, what is the size value it is returning for the state object? Just curious.

**Comment by lnicho** [comment]
@patrickhousley it's np at all. The size in our dev environment is 8479215 (+/- 500KB depending on what's being viewed). I'll get you a sample sent shortly.

**Comment by lnicho** [comment]
@patrickhousley I see I misread. I can get the troublesome NR agent enabled in one of our anonymous environments and share access with you early tomorrow. Thanks again for the help!

**Comment by patrickhousley** [comment]
@lnicho version 1.231.0 was released yesterday and includes the remove of the console.log wrapping. If you are still having performance issues after upgrading, please let us know.
