### ISSUE TITLE
NewRelic UI think the its running version 1 BrowserAgent so Distributed tracing doesn't work

### ISSUE THREAD

**Issue by joshuaswilcox** [newrelic/newrelic-browser-agent#475]
## Description

I have installed this in my react SPA and data is flowing into newrelic but the distributed tracing is not working. I have setup my SPA like this:

```const nrOptions = {
  init: {
    distributed_tracing: {
      enabled:true
    },
    privacy: {
      cookies_enabled:true
    },
    ajax: {
      deny_list:["bam.nr-data.net"]
    }
  },
  info: {
    beacon:"bam.nr-data.net",
    errorBeacon:"bam.nr-data.net",
    licenseKey:`${process.env.REACT_APP_NEW_RELIC_LICENSE_KEY_ID}`,
    applicationID:`${process.env.REACT_APP_NEW_RELIC_AGENT_ID}`,
    sa:1
  },
  loader_config: {
    accountID:`${process.env.REACT_APP_NEW_RELIC_ACCOUNT_ID}`,
    trustKey:`${process.env.REACT_APP_NEW_RELIC_ACCOUNT_ID}`,
    agentID:`${process.env.REACT_APP_NEW_RELIC_AGENT_ID}`,
    licenseKey:`${process.env.REACT_APP_NEW_RELIC_LICENSE_KEY_ID}`,
    applicationID:`${process.env.REACT_APP_NEW_RELIC_AGENT_ID}`
  }
}
new BrowserAgent(nrOptions)
```

## Steps to Reproduce

Install plugin and setup as above. Visit the distributed tracing section of your Browser application and you should seed
![Screenshot 2023-04-18 at 2 57 12 PM](https://user-images.githubusercontent.com/512078/232878790-2a416914-e62c-4826-9267-e8d1ef5b8560.png)

## Expected Behavior

I would expect that with the latest version of this plugin, to see distributed tracing attributes in the NewRelic UI

## Relevant Logs / Console output

No errors appear in the logs

## Your Environment

Happening on all browsers our users have been on (Chrome, Safari, Firefox) both mobile and desktop

**Comment by patrickhousley** [comment]
Thanks for reporting this issue @joshuaswilcox. Are you using the NPM package? If so, which version of the package are you using? If you load your app in the browser and filter the network requests going out, check the `v=` query parameter on the network calls to `bam.nr-data.net` and let me know what it says. Thanks.

**Comment by joshuaswilcox** [comment]
@patrickhousley, yes we are using  the NPM package, i see `v=0.1.23` in the query params

**Comment by patrickhousley** [comment]
Thanks @joshuaswilcox I managed to track down the issue. I will update the Jira ticket with details. The npm package is a pre-release and we appreciate you giving it a try. We will add this to our list of things we need to fix with it as we continue progressing on the package.
