### ISSUE TITLE
Publish browser agent as npm package

### ISSUE THREAD

**Issue by maveOne** [newrelic/newrelic-browser-agent#49]
## Summary

The current mechanism of using the NewRelic browser agent is to embed the code snippet - shown in the "Configure the agent" section in the `README.md` file - directly to the website.

An additional option might be to allow website developers to integrate the browser agent by using npm packages. This mechanism has several advantages, e.g. developers can decide when to update and test a new version of the browser agent. Furthermore, type-safety (when using TypeScript) could be enabled.

For the NewRelic node client, this feature is already implemented. See https://github.com/newrelic/node-newrelic/releases and https://www.npmjs.com/package/newrelic

## Desired Behavior

I am able to install the NewRelic browser agent with npm.

## Possible Solution

Standard npm publish / GitHub release mechanism. See https://github.com/newrelic/node-newrelic/releases and https://www.npmjs.com/package/newrelic

## Additional context

_none_

**Comment by metal-messiah** [comment]
Thank you for submitting your recommendation @maveOne! We'll need to explore this issue and consider where to prioritize it. There are some infrastructure changes we would need to make to make this happen, including switching to semver which would likely require some cascading changes to our supporting services.  That said, the values you noted are indeed evident and the main roadblocks for us are planning and prioritizing.  Thanks for the feedback and we will keep you posted.

**Comment by coreyarnold** [comment]
@maveOne I know it's been a while. We have started publishing an [NPM package](https://www.npmjs.com/package/@newrelic/browser-agent) that does basic functionality (manually capture errors) and are planning to get to feature parity soon. Have you by chance tried it out? Would love to get your feedback.
