### ISSUE TITLE
X-NewRelic-ID: undefined being set on same origin XHR requests

### ISSUE THREAD

**Issue by asos-rupeshghelani** [newrelic/newrelic-browser-agent#526]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

The agent is setting a request header unnecessarily when making same-origin XHR requests.

This [code](https://github.com/newrelic/newrelic-browser-agent/blob/6c5cbf0a2628d44a5792be9daea47818310117d4/src/features/ajax/instrument/index.js#L102) `if ('xpid' in loader_config && this.sameOrigin) {`  is always returning `true`, because the `xpid` key is [always present](https://github.com/newrelic/newrelic-browser-agent/blob/6c5cbf0a2628d44a5792be9daea47818310117d4/src/common/config/state/loader-config.js#L10).

And because `xpid` is `undefined`,  the header value is blindly set to `undefined`.

I expect a more robust check that `xpid` is set to a valid value.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

1. load browser agent Pro or higher with default config
2. make an XHR request to the same-origin
3. inspect the request headers of the XHR

## Expected Behavior
`X-NewRelic-ID` HTTP request header should not be set

## Actual Behavior
`X-NewRelic-ID: undefined ` HTTP request header is set

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version: any 
* ex: Operating System and version: any

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

<img width="849" alt="xpid_is_undefined" src="https://github.com/newrelic/newrelic-browser-agent/assets/34572581/9d5997b9-5e62-4eb9-b62c-6c4cd540800b">

<img width="601" alt="Fullscreen_11_05_2023__09_40" src="https://github.com/newrelic/newrelic-browser-agent/assets/34572581/3af8f327-668e-4a44-91eb-fa06b07b4525">

**Comment by bjfield** [comment]
@asos-rupeshghelani, thank you for noticing this bug and taking the time to enter a quality issue ticket. I've raised a PR (https://github.com/newrelic/newrelic-browser-agent/pull/531), which will likely make it into our next patch release. In a previous agent architecture, we didn't have that predefined configuration model, so the `xpid` property wasn't ever present unless explicitly set.
