### ISSUE TITLE
InteractionTimer leaks event listeners / debounces

### ISSUE THREAD

**Issue by indigane** [newrelic/newrelic-browser-agent#556]
**Note:** I hope this is the correct repository. I found my way here via searching the minified sources found in the browser.

## Description

InteractionTimer leaks event listeners / debounces. Or that is my best guess, you should look into it deeper.

If you leave a tab open for a long time (a few days) this will gradually slow down all click and keydown events.

For example, I left a tab open for a week, and click events took 6.2 seconds, and during that the most time was spent in a newrelic script doing hundreds of thousands of repeated `setTimeout` and `clearTimeout` calls.

I did another test on a completely different page, and in four days it slowed click events to 300ms, with the same symptoms.

Searching for the code in the performance trace points to this file https://github.com/newrelic/newrelic-browser-agent/blob/1ee675d232fb9a233c36ad0a2b998739fbaa1b8b/src/common/timer/interaction-timer.js

![image](https://github.com/newrelic/newrelic-browser-agent/assets/8503840/1edad455-2de4-4712-a5e1-3ac91b948def)

![image](https://github.com/newrelic/newrelic-browser-agent/assets/8503840/dff35a6c-3898-49d1-8e45-83f8a21d1d97)

## Steps to Reproduce

1. Have a page with newrelic monitoring and a JavaScript click event handler.
2. Leave the page open for a long time, for example multiple days, depending on the device.
3. (I didn't interact with the page much, but I'm not sure if some interaction is required.)
4. Start a performance trace in the browser and trigger the JavaScript click event handler. Or just wait long enough that it slows down to multiple seconds.

## Expected Behavior

Monitoring does not noticeably affect website performance.

## Relevant Logs / Console output

This line:

![image](https://github.com/newrelic/newrelic-browser-agent/assets/8503840/55bd8545-b3a8-4513-872c-6bcab772a165)

Points to this:

![image](https://github.com/newrelic/newrelic-browser-agent/assets/8503840/f1b2248e-d7c3-4cf4-91af-21ac22158c92)

## Your Environment

Chromium 113.0.5672.63

Also reproduced on Chrome on Android.

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by patrickhousley** [comment]
Hi @indigane. I just wanted to thank you for reporting this issue and let you know that I believe I found the bug. I will be opening a PR soon to resolve this issue.
