### ISSUE TITLE
Import Package in server giving not Found @newrelic/browser-agent/loaders/browser-agent

### ISSUE THREAD

**Issue by iamShashi** [newrelic/newrelic-browser-agent#563]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

**Tried Implementing new relic browser from the NPM package following the docs:**

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

**Here are steps i followed:**

import { BrowserAgent } from '@newrelic/browser-agent/loaders/browser-agent'**

// Populate using values in copy-paste JavaScript snippet.
const options = {
  init: { ... }, // NREUM.init
  info: { ... }, // NREUM.info
  loader_config: { ...} // NREUM.loader_config
}

// The agent loader code executes immediately on instantiation.
new BrowserAgent(options)**

As per NPM docs :

## Expected Behavior

Should not have given Error

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

My ENVS: 

- Node: >14.15
- NPM: 6.14
- @newrelic/browser-agent: "^1.233.0"
- Webpack: "4.3.0"

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by patrickhousley** [comment]
Closing. Not enough information provided. Please provide a reproduction for the issue and re-open the issue if you are still having this issue.

**Comment by matthew-spahr** [comment]
also having the same issue. `Cannot find module '@newrelic/browser-agent/loaders/browser-agent'.` when starting my application. package is present node_modules and now warnings thrown from VSCode. import statement within angular project: 
```
// eslint-disable-next-line import/no-unresolved
import { BrowserAgent } from '@newrelic/browser-agent/loaders/browser-agent';
```

**Comment by patrickhousley** [comment]
Hi @matthew-spahr and thanks for reporting this issue. Can you provide a simple reproduction case of this issue? Can you provide the version of Node and NPM you are using? Is this possibly an issue with Angular and it's build system? We have tests in the repository that import the NPM package and verify it is working.

**Comment by joshuaswilcox** [comment]
Getting the same thing here as well with:
Node 14.20.1
NPM 6.14.17.
@newrelic/browser-agent: "^1.236.0"

Here is the build trace

```
[0] multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src/index 52 bytes {main} [built]
[./node_modules/react-dom/index.js] 1.33 KiB {main} [built]
[./node_modules/react-redux/es/index.js] 776 bytes {main} [built]
[./node_modules/react/index.js] 190 bytes {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 4.29 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {main} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {main} [built]
[./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {main} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {main} [built]
[./src/index.tsx] 1.25 KiB {main} [built]
    + 803 hidden modules

ERROR in ./src/index.tsx
Module not found: Error: Can't resolve '@newrelic/browser-agent/loaders/browser-agent' in '/Users/josh/webapps/boundless/admin/src'
 @ ./src/index.tsx 5:0-77 34:4-16
Child HtmlWebpackCompiler:
     1 asset
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 614 bytes {HtmlWebpackPlugin_0} [built]
ℹ ｢wdm｣: Failed to compile.
```
