### ISSUE TITLE
UnhandledRejection error while loading the agent 1.235.0

### ISSUE THREAD

**Issue by ilario-pierbattista** [newrelic/newrelic-browser-agent#599]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Starting from yesterday evening (2023-06-22 17:00 UTC), I'm getting the following error while loading the agent in browsers with strict privacy settings:

> UnhandledRejection
Non-Error promise rejection captured with value: undefined

It's similar to #392. In the browser console I see chunks loading failures, and then the error `Uncaught (in promise)`.

The agent is injected dinamically in HTML by the PHP agent.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

Use a browser with strict privacy settings. It will block the requests to `https://js-agent.newrelic.com`.

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

Even if the browser blocks the agent download I expect to get only warnings in console. Rejections should be handled.

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

Sample warnings:
```
New Relic: Downloading runtime APIs failed... 
New Relic: A problem occurred when starting up session manager. This page will not start or extend any session.
  ChunkLoadError: Loading chunk 860 failed.
  (error: https://js-agent.newrelic.com/860.e997904f-1.235.0.min.js)
New Relic: Downloading and initializing page_view_event failed...
  ChunkLoadError: Loading chunk 412 failed.
  (error: https://js-agent.newrelic.com/lazy-feature-loader.0ba331d7-1.235.0.min.js)
[...] and so on
```

Error:
```
Uncaught (in promise) undefined [A:6:32604](https://website/page)
    a https://website/page:6
    InterpretGeneratorResume self-hosted:1359
    AsyncFunctionThrow self-hosted:760
    (Asinc.: async)
    importAggregator https://website/page:6
    nrWrapper https://website/page:6
    (Asinc.: EventListener.handleEvent)
    nrWrapper https://website/page:6
    s https://website/page:6
    o https://website/page:6
    importAggregator https://website/page:6
    F https://website/page:6
    start https://website/page:6
    forEach self-hosted:203
    start https://website/page:6
    <anonima> https://website/page:6
    <anonima> https://website/page:6
    <anonima> https://website/page:6
    <anonima> https://website/page:6
```

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* php NR agent version: 10.5.0.317
* the agent is configured to auto inject the js script

## Additional context

Similar issues #392 

[TIP]:  # ( Add any other context about the problem here. )

**Comment by patrickhousley** [comment]
Thanks for reporting this issue @ilario-pierbattista. We will investigate why the chunk loading errors are not being caught.

**Comment by AKovtunov** [comment]
I encountered the same issue, any solution?

**Comment by ilario-pierbattista** [comment]
Hi @patrickhousley,

now it started to use the 1.236.0 version, and it started to fail with:

> ChunkLoadError: Loading chunk 412 failed.
(error: https://js-agent.newrelic.com/lazy-feature-loader.2f55ce66-1.236.0.min.js)

It seems a regression of #392

**Comment by ilario-pierbattista** [comment]
@cwli24 nope, my bad, it was just a warning.
Some times it gives `Unhandled Promise Rejection: Failed to fetch` while posting to `https://bam.nr-data.net`.
Currently I'm not able to reproduce it, neither with a privacy strict browser.

**Comment by tavito** [comment]
> @cwli24 nope, my bad, it was just a warning. Some times it gives `Unhandled Promise Rejection: Failed to fetch` while posting to `https://bam.nr-data.net`. Currently I'm not able to reproduce it, neither with a privacy strict browser.

I'm getting the same error. It started on Jun 30...

**Comment by matejbasic** [comment]
Any progress with the `Unhandled Promise Rejection: Failed to fetch` error?
I was trying to reproduce it but without any success

**Comment by matejbasic** [comment]
thank you @cwli24

**Comment by patrickhousley** [comment]
@matejbasic @ilario-pierbattista @tavito @matejbasic We recently released version 1.237.1 of the browser agent. Could you please let us know if this issue is still persisting? For APM injected apps, you may need to restart your APM instrumented applications.

**Comment by ilario-pierbattista** [comment]
@patrickhousley it seems to be fixed, thanks

**Comment by tavito** [comment]
@patrickhousley it seems to be fixed here too, thanks!

**Comment by vekien** [comment]
Hello,

We are still getting version 1.236.0, we've cleared cache, redeployed (ecs+docker), rebuilt images, rebuilt php-agent, nothing is working and we're still getting 1.236.0

Has this not been published yet or something? It's causing us a huge amount of issues because it flags on Sentry, so we're hoping to get this fix ASAP.

**Comment by vekien** [comment]
What is the copy/paste install method?

This is how we have our agent installed (it's Docker)

```
RUN wget https://download.newrelic.com/php_agent/archive/10.11.0.3/newrelic-php5-10.11.0.3-linux-musl.tar.gz \
    && tar -xf newrelic-php5-10.11.0.3-linux-musl.tar.gz \
    && cd newrelic-php5-10.11.0.3-linux-musl \
    && NR_INSTALL_USE_CP_NOT_LN=1 NR_INSTALL_SILENT=1 ./newrelic-install install
```

![Screenshot 2023-08-10 at 18 28 37](https://github.com/newrelic/newrelic-browser-agent/assets/270800/51643b58-93e8-4cb4-9f6f-f1df60f9dde3)

And our application is still fetching 1.236.0, it's not cached either as we're getting thousands of Sentry's from over 100+ users.

**Comment by patrickhousley** [comment]
@vekien You will want to reach out to the New Relic support team as this seems like a possible issue with the PHP APM agent. It should automatically get the newest version of the browser agent. We, the browser agent team, does not have any settings set right now to force this version. Sorry I could not help further.

**Comment by matejbasic** [comment]
@patrickhousley no errors reported in last week, seems to be working fine now, thank you! :blush:
