### ISSUE TITLE
Chrome in iOS: Diagnose which AjaxRequest (and some BrowserInteraction) events not shown for iPhone and Chrome

### ISSUE THREAD

**Issue by rr0214** [newrelic/newrelic-browser-agent#60]
Dependency: Before determining the size of work necessary to resolve this issue, we need to determine which versions of Chrome for iOS are incompatible with the XHR feature and which should be feature-gated.

Rebecca Note: We need to get estimations on total amount of traffic impacted.

There are still some context details on this ticket: https://docs.google.com/document/d/15Z3v_SGCFCqyW5Cib2ODdYHIaPyQLv-ZmU4uzr8e-RA/edit?usp=sharing

Update 7/7/2020: Because of the behavior of older versions of Chrome for iOS, the browser agent has not enabled XHR or Session Trace instrumentation in that browser. This means AjaxRequest and Span events will not be harvested for traffic from Chrome for iOS. It also means BrowserInteraction duration measurements will not include any network (XMLHttpRequest and Fetch) related duration. BrowserInteractions from Chrome for iOS will currently show NavigationTiming API related values, but no ajaxCount and little to no value for duration.

The work this ticket now represents is removing that override, instrumenting the latest version Chrome for iOS, confirming whether the data produced is valid and ticketing the necessary work to release a version of the agent which instruments SPA on Chrome for iOS for versions older than the tested working version. See comments below on how to locally inject and test the agent in Chrome on iOS.

 

We cannot see any BrowserInteraction events from iPhone X using Chrome 80. I have tried using emulation, and that reports using Safari. They have implemented the suggestion from the other ticket, https://newrelic.zendesk.com/agent/#/tickets/392985 

Please see Zendesk Support tab for further comments and attachments.

other comments from Jira card:
Aubrey: Attaching another related behavior, currently creating custom interactions using the SPA API in Chrome for iOS causes 1000s of interactions with no timing data to be created, this should hopefully be resolved if/when SPA was properly enabled for this user agent.

Lindsy: Updated this ticket to include AJAX request events per previous ticket JS-5807: Chrome in iOS and iPad is not reporting XHRREJECTED

Notes form comments in that ticket:Ticket that triggered this inquiry:
https://newrelic.zendesk.com/agent/tickets/344795

Impact is significant since it's causing them to miss AJAX data on a retail site. They are open to implementing a workaround if one is available. I will ask Dublin support team to do a temperature check with this information.

Closing 5087 to work from this ticket for both issues as they are the same culprit.

Aubrey: 
For whoever picks up this ticket to inject the agent and determine whether we can enable XHR and SPA for Chrome, this is the process I used to inject the agent on customer or local sites on iOS:

Proxy traffic between iOS and Charles to inspect network requests made by Chrome. Use. this tutorial to enable and trust certificate: https://benoitpasquier.com/charles-ssl-proxy-ios/

Use Charles' external proxy settings to forward traffic to agent in the middle. Replace the port in the screenshot with the port agent-in-the-middle exposes

**Comment by aubreymasten** [comment]
Context: https://source.datanerd.us/browser/browser_agent/commit/10611fceebb081dbabeeedc8fc04f064704a958a

**Comment by coreyarnold** [comment]
moved to JIRA: https://issues.newrelic.com/browse/NR-4525
