### ISSUE TITLE
Property 'noticeError' does not exist on type 'MicroAgent'

### ISSUE THREAD

**Issue by jamesarosen** [newrelic/newrelic-browser-agent#608]
The types for `MicroAgent` don't include `noticeError` despite that appearing in the docs.

## Description

The README has this code:

```js
const microAgent1 = new MicroAgent(options_1)
// ...
// manually handle a JavaScript Error with microAgent1
try{
  ...
} catch(err) {
  microAgent1.noticeError(err)
}
```

But when I try that locally, TypeScript complains:

> Property 'noticeError' does not exist on type 'MicroAgent'.ts(2339)

## Steps to Reproduce

1. Install `@newrelic/browser-agent@1.236.0`
2. Create a TypeScript file with the following contents:

```ts
import { MicroAgent } from "@newrelic/browser-agent/loaders/micro-agent";

const agent = new MicroAgent({ /* some configuration */ });

try {
  throw new Error('test')
} catch (e) {
  agent.noticeError(error);
}
```

## Expected Behavior

The code compiles

## Your Environment

I haven't yet gotten to a runtime environment, but it will be running in Fastly's Compute@Edge, which mimics a ServiceWorker environment.

**Comment by jamesarosen** [comment]
This sort of works:
```ts
import { MicroAgent } from "@newrelic/browser-agent/loaders/micro-agent";
import type { setAPI } from "@newrelic/browser-agent/loaders/api/api";

type NewRelicAPI = ReturnType<typeof setAPI>;

const agent = new MicroAgent({ /* config */ })
(agent as unknown as NewRelicAPI).noticeError(error, {});
```

A minor issue is that the second argument -- `customAttributes` -- isn't optional in the TypeScript types.

**Comment by cwli24** [comment]
Hi @jamesarosen , all the code excerpts in the README are in JS, as we do not have support for TS.

There's however a community-created typings for our agent's interface at: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/new-relic-browser . Please note we're not responsible for this typing. For more, see thread on this: https://forum.newrelic.com/s/hubtopic/aAX8W0000008YeBWAU/typescript-for-browser-agent.

**Comment by jamesarosen** [comment]
> we do not have support for TS

You might want to remove this from your `package.json` then:

```
"types": "./dist/types/index.d.ts",
"typesVersions": {
  ">=4.2": {
    "*": [
      "dist/types/*"
    ]
  }
},
```

Having that in the published `package.json` implies (1) that you do support TypeScript and (2) that consumers don't need to rely on `DefinitelyTyped` for this package.

**Comment by patrickhousley** [comment]
Typescript types generation cannot determine the actual types due to the dynamic nature of the agent. I will look into fixing the types generation in our build process.

**Comment by jamesarosen** [comment]
> Typescript types generation cannot determine the actual types due to the dynamic nature of the agent

I think you actually can by applying type predicates when mixing in the capabilities in `configure/configure` and `api/api`, though that would probably require writing the library in TypeScript rather than trying to generate types during the build process.
