### ISSUE TITLE
LCP continues to be reported after page is hidden

### ISSUE THREAD

**Issue by martinkuba** [newrelic/newrelic-browser-agent#66]
## Description

The NR agent continues to record Largest Contentful Paint after the page changes visibility. This is a different from the WebVitals library, which stops recording when the page is hidden (e.g. by switching tab).
https://github.com/GoogleChrome/web-vitals/blob/main/src/getLCP.ts#L68

In order to capture the same values as the Google official library, we should change this behavior.

Effort: Small

**Comment by rr0214** [comment]
Effort: Small

**Comment by aubreymasten** [comment]
Fixed with PR #115
