### ISSUE TITLE
JSErrors on MicroAgent don't report the events

### ISSUE THREAD

**Issue by maac4422** [newrelic/newrelic-browser-agent#666]
## Description

I'm using MicroAgent but I don't receive the JSErros on the new relic, I tested it forcing a throw exception in my app, and it doesn't reflect that event.

NOTE: I tried the same with Agent and the event is reported fine.

## Steps to Reproduce

```
import { MicroAgent } from '@newrelic/browser-agent/loaders/micro-agent'
// @ts-ignore
import { JSErrors } from '@newrelic/browser-agent/features/jserrors'
// @ts-ignore
import { Ajax } from '@newrelic/browser-agent/features/ajax'
// @ts-ignore
import { Metrics } from '@newrelic/browser-agent/features/metrics'
// @ts-ignore
import { SessionTrace } from '@newrelic/browser-agent/features/session_trace'

const newRelicOptions = {
  init: {distributed_tracing: {enabled: true}, privacy: {cookies_enabled: true}, ajax: {deny_list: [""]}},
  info: {beacon: "", errorBeacon: "", licenseKey: NEW_RELIC_LICENSE_KEY, applicationID: NEW_RELIC_AGENT_ID, sa: 1},
  loader_config: {accountID: NEW_RELIC_ACCOUNT_ID, trustKey: NEW_RELIC_ACCOUNT_ID, agentID: NEW_RELIC_AGENT_ID, licenseKey: NEW_RELIC_LICENSE_KEY, applicationID: NEW_RELIC_AGENT_ID},
}

function createNewRelicLogger() {
  let agent: MicroAgent | null = null

  if (!agent) {
    agent = new MicroAgent({
      ...newRelicOptions,
      features:[
        JSErrors,
        Ajax,
        Metrics,
        SessionTrace
      ]
    })
  }

  function error(error: string | Error, customAttributes?: object | undefined) {
    agent?.noticeError(error, customAttributes)
  }

  function start(){
    agent?.start()
  }

  return {
    error,
    start
  }
}

const newRelicLogger = createNewRelicLogger()

export default newRelicLogger
```

## Expected Behavior

The throw exception report correct on the new relic dashboard

## Your Environment

- React with Vite, and Typescript.

- Browser: Google Chrome

**Comment by metal-messiah** [comment]
Hey 👋 @maac4422 

Thanks for the report. For clarity, the micro agent is actually intended to be "api"-driven only and not auto-instrumented. It will not automatically observe and report thrown errors. It is meant to be light-weight, able to be instantiated multiple times on a page, and does so by being "manual" only and does not wrap around all the browser globals the normal agent build does. For errors, the micro-agent is only compatible with ".noticeError" for handling caught exceptions passed into it. 

https://www.npmjs.com/package/@newrelic/browser-agent#deploying-one-or-more-micro-agents-per-page

Please let us know if you need more information on the micro agent, happy to chat through it.

**Comment by maac4422** [comment]
Hey @metal-messiah 
thanks for the answer, I will create my own error handler, to listen to the errors in the app. 😄 .

Just another question, but I can open another issue, why do I need add `// @ts-ignore` in all the features, the agents work fine, but apparently the features missing the types

**Comment by cwli24** [comment]
@maac4422 out of curiosity, what's the exact error you get if you don't ts-ignore? We have declarations auto generated for the features. 🤔

**Comment by maac4422** [comment]
@cwli24 
`Cannot find module '@newrelic/browser-agent/features/jserrors' or its corresponding type declarations.`

**Comment by patrickhousley** [comment]
@maac4422 what verion of typescript and node are you using? Can you provide a copy of your tsconfig?

**Comment by patrickhousley** [comment]
@maac4422 what version of typescript are you using? Do you get the error when running `tsc` or only when running the webpack build?

**Comment by maac4422** [comment]
@patrickhousley  only have the error when run tsc

The typescript version is: 4.9.5
<img width="818" alt="Screenshot 2023-08-30 at 10 50 16 AM" src="https://github.com/newrelic/newrelic-browser-agent/assets/15006454/ef0e24f3-ba72-4c92-aca3-1c8c3fd1ea77">

**Comment by maac4422** [comment]
@patrickhousley Here is a clean project to reproduce the issue

Run:
```
npm install
npm run dev
```
[test-new-relic.zip](https://github.com/newrelic/newrelic-browser-agent/files/12486445/test-new-relic.zip)

**Comment by villelahdenvuo** [comment]
I'm also getting TS errors on 1.238.0:

<img width="895" alt="Screenshot 2023-08-31 at 15 40 20" src="https://github.com/newrelic/newrelic-browser-agent/assets/633524/8b62a9ae-13ac-492f-b847-368bdbb506c2">

**Comment by patrickhousley** [comment]
Thanks @maac4422 I found the issue.
