### ISSUE TITLE
Browser Agent Module Not found

### ISSUE THREAD

**Issue by hemanthkumaryerra** [newrelic/newrelic-browser-agent#667]
#647
Opened a new ticket as I am still facing the issue and previous ticket was closed. 
Attached screenshot for your reference
![IMG_20230829_152457215~2](https://github.com/newrelic/newrelic-browser-agent/assets/48920003/c46fe27c-fd6c-4d9c-92e7-13aa5eb09d32)

**Comment by patrickhousley** [comment]
Thanks for reporting this issue. Sorry we closed the previous issue, I thought it was resolved. Are you running `tsc` when you get this error? Could you provide a small reproduction example?

**Comment by patrickhousley** [comment]
Morning @hemanthkumaryerra We have not gotten a response back on this issue. We did recently release 1.239.0 with fixes to the types declaration in our package.json. Please give that a try. If you are still having issues, feel free to re-open this issue and provide a small reproduction or you may reach out support team at https://support.newrelic.com/s/

**Comment by hemanthkumaryerra** [comment]
We are not running any typescript commands. I tired with latest browser Agent package still it's the same.
I am running the application using npm start. ![Screenshot_20230906-120713-111.png](https://github.com/newrelic/newrelic-browser-agent/assets/48920003/e19d7959-ae99-4ddb-930d-afdbf69c9bc2)
