### ISSUE TITLE
Micro Agent - Stop browser APP sending metricts

### ISSUE THREAD

**Issue by Khaos93** [newrelic/newrelic-browser-agent#719]
Hi

I want to know if is there a method or mechanism available to intentionally halt the browser agent from sending metricts to New Relic

**Comment by patrickhousley** [comment]
Hi @Khaos93 can you elaborate more on what data you are not wanting to send and what your current installation/implementation of the browser agent looks like?

**Comment by Khaos93** [comment]
Hi @patrickhousley 

I have an application embedded within other client applications. The issue I'm encountering is that when the embedded app is unmounted within the parent application, the New Relic client continues to send metrics even though the initializing application is no longer active. 


``agent = new MicroAgent({
    configuration
})
agent.start``

we are using the verion 1.238.0

**Comment by patrickhousley** [comment]
@Khaos93 I know this might be a tough ask but is there any way you could create a simple app to highlight this use-case for us? You can zip up the source and drop it here.

**Comment by FranciscoKloganB** [comment]
An explicit stop feature is also desired by us in the browser agent.

We are allowing the user to opt-in to instrumentation and session replay.

We explicit call the `start` on the after he `opts-in` and we would like to call `stop` if he opts out.

**Comment by edelgado** [comment]
+1 I'd love to be able to disable features from the running instance of the agent: `window.newrelic`. 

I tried adding new keys to `window.newrelic.init` like:

```js
window.newrelic.init.spa = {enabled: false};
```

But that seems to have no effect.

**Comment by Ivan-accedo** [comment]
Hi!

I also need to disable to stop the browser agent, e.g. when the user declines the tracking after the `newrelic.start()`.

**Comment by metal-messiah** [comment]
Relates to #1175

**Comment by metal-messiah** [comment]
A feature request has been elevated to our PM around this topic, for evaluation and prioritization.  Thank you for contributing @Ivan-accedo @edelgado @FranciscoKloganB @Khaos93 

https://new-relic.atlassian.net/browse/NR-314711?atlOrigin=eyJpIjoiNDllNjVkMzBkZjYzNGZlNDgxMjAwODdkZGJmMzQwNjEiLCJwIjoiaiJ9
