### ISSUE TITLE
Remove references to Opera from our testing matrix

### ISSUE THREAD

**Issue by rr0214** [newrelic/newrelic-browser-agent#72]
Opera is no longer a supported browser in SauceLabs (source). While it was supported, we experienced issues with it that lead us to explicitly exclude it from certain tests in the agent (search for `.exclude('opera@<=12')` in the agent repo for examples), these are unnecessary now, those and any other references to opera should be cleaned up and it should be documented somewhere than Opera may not be an officially supported browser.

**Comment by rr0214** [comment]
Effort: Small

**Comment by aubreymasten** [comment]
If we are deprecating support for older Opera versions, we may also want to cleanup Opera specific code in new agent versions: https://github.com/newrelic/newrelic-browser-agent/blob/ea23cdb3208ec24b1646187bf7f0ee0ef61939c4/feature/err/aggregate/compute-stack-trace.js#L271-L412
