### ISSUE TITLE
Running agent tests does not work on Windows

### ISSUE THREAD

**Issue by rr0214** [newrelic/newrelic-browser-agent#73]
Running `npm run test` on Windows errors with message:

'tools' is not recognized as an internal or external command.

Even when using `node` at the beginning of the command does not seem to run tests.

- small effort

**Comment by cwli24** [comment]
> Even when using node at the beginning of the command does not seem to run tests.
@rr0214 added node to the beginning of the test command inside the base `package.json` file, like so:
<img width="517" alt="image" src="https://user-images.githubusercontent.com/28714891/180826623-6de52f27-482b-49f2-8bed-aeb9db7539df.png">
should make it functional. Please confirm this.
