### ISSUE TITLE
Agent can cause memory issues when it runs after the window load event

### ISSUE THREAD

**Issue by martinkuba** [newrelic/newrelic-browser-agent#76]
## Description

When the initial agent script (loader) executes after the load event, it will never load the second part of the agent. It will also continue buffering data indefinitely.

There is a failsafe mechanism to stop collecting data when the second part of the agent does not load within 30 seconds. But this mechanism is setup when the window load event fires. Therefore, if the event never fires, data will continue to be collected in a buffer causing the web page to eventually run out of memory. 

## Expected Behavior

The agent should detect if the window load event has already occurred, and either initiate the second script download or abort.

**Comment by rr0214** [comment]
Not a confirmed problem. We will close this issue.
