### ISSUE TITLE
Distributed Tracing Doesn't Seem to Work With Built Files

### ISSUE THREAD

**Issue by wrumsby** [newrelic/newrelic-browser-agent#77]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

I've tried using the built files to host the SPA agent locally with a configuration like the following:

```html
<script type="text/javascript">
  window.NREUM||(NREUM={});
  NREUM.init = {
    distributed_tracing: {
      enabled: true,
      cors_use_newrelic_header: true,
      cors_use_tracecontext_headers: true,
      allowed_origins: [/* array of strings of origins, e.g. 'https://example.com', 'https://mydomain' */]
    },
    privacy: {
      cookies_enabled: true
    }
  };
  NREUM.info = {
    licenseKey: "/* my license key */",
    applicationID: /* my application id */,
    agent: "https://MY_CDN/nr-spa.js"
  };
</script>
<script src="https://MY_CDN/nr-loader-spa.js"></script>
```

It appears that most of the standard browser monitoring works, but distributed tracing does not.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
1. clone this project
2. run `npm run build`
3. upload the generated `nr-spa.js` and `nr-spa-loader.js` to a CDN, web server, etc.
4. initialise the agent to use distributed tracing with a set of allowed domains that are also configured to support distributed tracing headers
5. in a browser app using the generated scripts make XHR requests which should be included in distributed traces

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )
* AJAX requests are made with tracestate, traceparent and newrelic headers
* requests appear in Distributed Tracing

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* Chome 91.0.4472.101
* OS X 11.4

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by aubreymasten** [comment]
Hey @wrumsby, thanks for all the detail here! You may need to include some additional attributes in NREUM.info for distributed tracing to work. If you add `accountId` and `agentId` to that config block, are the headers still not showing up on outgoing requests?

The agent checks these attributes before generating Distributed Tracing headers here:
https://github.com/newrelic/newrelic-browser-agent/blob/ef2a15cdf44d80f5d51d7ba9b57672546b89ca1d/feature/xhr/instrument/distributed-tracing.js#L28-L30

You may also want to add the `trustKey` attribute and give it the same value as `accountId` if traces aren't showing up in the UI.

Let me know if that works or you run into other issues!

**Comment by wrumsby** [comment]
Hello @aubreymasten, yes it does seem I need to include the following to get distributed tracing to work:

```js
NREUM.loader_config = {
  accountID: /* my account id */,
  trustKey: /* my account id */,
  agentID: /* my application id */
};
```

I'll close this issue as this now works for me, but it might be worth including more details about `init`, `info` and `loader_config` in the agent documentation.
