### ISSUE TITLE
Support zone.js style stacktrace

### ISSUE THREAD

**Issue by tanaka-takayoshi** [newrelic/newrelic-browser-agent#78]
## Summary

Since [zone.js](https://www.npmjs.com/package/zone.js?activeTab=readme) rewrites the stack trace, New Relic agent doesn't recognize the stack trace in some errors when zone.js is using.
Can we support zone.js style stack trace to show all stack traces?

## Desired Behavior

[NOTE]: Show all stack traces

note: https://github.com/angular/angular/issues/31588

## Additional context

This issue was previously discussed in GTSE-9182 and the customer and New Relic engineering decided to submit this feature request.

**Comment by rr0214** [comment]
Research: How often do we get errors with no stack trace. How often do we get stack traces but can't parse it.
