### ISSUE TITLE
Long error/log messages in critical path bundle

### ISSUE THREAD

**Issue by villelahdenvuo** [newrelic/newrelic-browser-agent#787]
## Summary

I noticed that the bundle generated by webpack when importing the browser agent contains multiple long error / log strings e.g. 

> "Call to agent api setUserId failed. The js errors feature is not currently initialized."

> "API/noticeError/called"

> "Failed to execute setCustomAttribute.\nName must be a string type, but a type of <".concat(typeof v,"> was provided."

## Desired Behavior

Critical path bundle size should be minimized.

## Possible Solution

Use error codes instead and documentation to explain them in depth? More lazy loading?

## Additional context

JavaScript go brrr. 😄 
![image](https://github.com/newrelic/newrelic-browser-agent/assets/633524/4b2503bb-8462-46cf-be05-ef4ebe1f4d8a)

**Comment by patrickhousley** [comment]
Hi @villelahdenvuo . We reviewed our code bundles and talked through this request internally and have decided not to pursue it at this time. The strings that could be changed to codes accounts for less than 5kb of the minified bundle. When compressed using gzip or brotli, that size goes even further down to less than 1kb. The amount of effort to implement and maintain this change plus the need for customers to go to the docs to research the codes compared to anticipated savings is too high for us to proceed at this time.
