### ISSUE TITLE
Issue with Dynamically Adding Browser Agent Snippets between Environments through GTM or other methods

### ISSUE THREAD

**Issue by dvrs-brad** [newrelic/newrelic-browser-agent#788]
## Description

We are encountering issues while trying to dynamically add two different browser agent snippets between our Production and Development environments using the same code base. We decided to incorporate the snippets using Google Tag Manager (GTM).

## Setup:

We have configured separate GTM containers for Production (Prod) and Development (Dev) environments.
Each environment is loaded with respective GTM IDs specified in our environment files.

## Problem:

When adding the snippets via GTM, we’re facing a linting error. Despite attempts to fix the error, GTM specifies the error location as line 2 col 32,000, which isn’t helpful.

When we tried to add the snippets directly to our code base dynamically via environment type, we encountered an "HTTP error content too large" in some browsers.  This is actually what lead us to try GTM

Has anyone encountered this issue before or found a workaround, either by resolving the linting error in GTM or through another method?

**Comment by patrickhousley** [comment]
@dvrs-brad Can you provide more details around your project setup and what led you to try GTM? Maybe a small reproduction of the `HTTP error content too large` error message?

**Comment by patrickhousley** [comment]
Yea that's very helpful @dvrs-brad , thanks for the details. Is your project pure react or are you using NextJS? You may want to checkout [this](https://docs.newrelic.com/docs/browser/single-page-app-monitoring/troubleshooting/angular-truncated-copy-paste-snippet/) troubleshooting article. I know it specifically calls out angular but I have seen the same issue in NextJS too where NextJS either cuts off the content or throws an error.

**Comment by dvrs-brad** [comment]
Thanks @patrickhousley.

 It is pure react.  I read that article and didn't have the same problem they described.  Mine wasn't  cut off.  For some reason without adding it through index.html it triggers a 413.  

Do you know if there is a way to tell New Relic which environment it is based on possibly the URL?  Maybe there is a way to handle this using one script and through settings in New Relic?  Didn't see any way but wanted to rule that out as a possibility.

**Comment by patrickhousley** [comment]
You may still be able to do something like what that article is describing. Create two JS files in your `assets` directory; `newrelic.js` for production and `newrelic.preprod.js` for preprod environments. You can then insert a `script` element with a `src` attribute pointing to the correct script depending on which environment you are in. It is not exactly a supported installation method but should be OK as long as you put the script toward the top of the `head` in your HTML (below any `meta` elements) and do not use `async` or `defer`.

**Comment by dvrs-brad** [comment]
@patrickhousley Thank you.  Starting with the logic from the article you linked to with a little other research I have it loading conditionally in my index.html.  Google Analytics is loading before the new relic script.  Hopefully that isn't a huge issue.  It is a little hard to control that order.  I'll push to dev and test tomorrow.

**Comment by patrickhousley** [comment]
@dvrs-brad That's good to hear. It would be most ideal to load the agent before any other scripts but you can check the network log in the browser dev tools and the New Relic dashboards to make sure you are getting all the data. I am going to close this issue for now. If you still need help, feel free to reopen it with more details.
