### ISSUE TITLE
Support browser agent npm package inside SSR application

### ISSUE THREAD

**Issue by LitHaxor** [newrelic/newrelic-browser-agent#802]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

```js
"use client";
import React from "react";
import { BrowserAgent } from "@newrelic/browser-agent/loaders/browser-agent";

const SetupMonitoring = () => {
  const options = {
    init: {
      distributed_tracing: { enabled: true },
      privacy: { cookies_enabled: true },
      ajax: { deny_list: ["bam.nr-data.net"] },
    },
    info: {
      accountID: "xxxxx",
      trustKey: "xxxx",
      agentID: "xxxx",
      licenseKey: "xx-xxxx",
      applicationID: "xxx",
    },
    loader_config: {
      beacon: "xx.nr-data.net",
      errorBeacon: "xx.nr-xx.net",
      licenseKey: "xx-xx",
      applicationID: "xx",
      sa: 1,
    },
  };

  new BrowserAgent(options);
  return <div></div>;
};

export default SetupMonitoring;

```

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version: 
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by LitHaxor** [comment]
Also most useless documentation I've ever seen for this

https://www.npmjs.com/package/@newrelic/browser-agent

**Comment by samuelcole** [comment]
I just worked through this: the problem is that the package determines the `globalThis` context on _import_, and those of us using Next.js or other SSR isomorphic frameworks will usually import the library on the server-side, even if we don't intend to use it server-side.

To fix it, I imported the library dynamically in a `useEffect`:
``` typescript
  useEffect(() => {
    if (typeof window !== "undefined") {
      (async () => {
        const { BrowserAgent } = await import(
          "@newrelic/browser-agent/loaders/browser-agent"
        );
        new BrowserAgent({
```

but my understanding is that the BrowserAgent is supposed to be available ASAP, so this will just slow it down with an async import.

I highly recommend calculating `globalThis` from inside the constructor/init process, so that the library does not throw exceptions just for being imported server-side.

**Comment by patrickhousley** [comment]
> Also most useless documentation I've ever seen for this
> 
> https://www.npmjs.com/package/@newrelic/browser-agent

Thank you @LitHaxor for your feedback. Could you please provide more specifics around what the documentation is not accomplishing? We are also an open source project and welcome contributions in the form of pull requests.

**Comment by patrickhousley** [comment]
Thanks @samuelcole for providing more information on this issue. We will take this as a feature request to support SSR applications. Currently, the browser agent does expect to be executed within a browser context.

**Comment by patrickhousley** [comment]
@samuelcole Can you try the below steps for this issue?
1. Create a new file `newrelic.ts` in your project, preferrably in the `libs` directory or somewhere where you can import from your apps main layout
2. Move the import and agent instantiation into that file
3. At the top of the file, put `'use client'`. This needs to be on the first line of the file by itself
4. Import the `newrelic.ts` file in your main layout file and rebuild/retest

This should force NextJS to import and execute the browser agent only on the client side

**Comment by LitHaxor** [comment]
Thanks to the new relic team
