### ISSUE TITLE
Module not found: Can't resolve '@newrelic/browser-agent/loaders/browser-agent'

### ISSUE THREAD

**Issue by mylenasantos** [newrelic/newrelic-browser-agent#823]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

I have done all the New Relic configuration in my app... But when a Installed the agent library, occurred this error: 

Module not found: Can't resolve '@newrelic/browser-agent/loaders/browser-agent'

I'm using React.js, with create react app.
 

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

this steps: https://www-development.newrelic.com/blog/how-to-relic/custom-instrumentation-with-the-new-relic-browser-agent

import { BrowserAgent } from '@newrelic/browser-agent/loaders/browser-agent'; 
yarn start

## Relevant Logs / Console output

./src/index.js
Module not found: Can't resolve '@newrelic/browser-agent/loaders/browser-agent'

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

node version: 16.16.0
npm version: 8.11.0
react version: 16.7.0
OS: MacBook Air
Browser: Chrome

**Comment by mylenasantos** [comment]
@newrelic/browser-agent@1.248.0

**Comment by patrickhousley** [comment]
@mylenasantos Can you please provide a small reproduction of the issue?

**Comment by patrickhousley** [comment]
Hi 👋 @mylenasantos . If last week was a holiday, I hope you had a great one. Catching back up on issues here, I would like to try and get more information on your issue you reported here. We have internal tests that verify our imports are working so this may be an issue with some part of your project setup. The easiest way to verify and test would be if you could provide a small reproduction case, possibly as a zip attached here that I can download or as a github repo or gist. I could try to reproduce the setup locally but with the state of the JS ecosystem these days, there could be a million differences.

**Comment by patrickhousley** [comment]
Hi @mylenasantos I am going to close this issue due to inactivity. Feel free to reopen with the additional information requested,.
