### ISSUE TITLE
TraceIds are not random when browser supports web crypto API

### ISSUE THREAD

**Issue by paddyo** [newrelic/newrelic-browser-agent#826]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

TraceIds being generated for distributed tracing always end in `00`, but the W3C spec for traceids should be random (https://www.w3.org/TR/trace-context/#considerations-for-trace-id-field-generation).

## Steps to Reproduce

With distributed tracing enabled and using version 1.248, observe the traceids sent by the browser agent, on a browser that supports the web crypto API. Alternatively use the steps in this gist: https://gist.github.com/paddyo/c861c640a2328aaf0d09d30c103bb3dd to target the library code directly (requires Node 21.2.0).

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

The generate traceId should be as observably random as possible. No character in the string should be guaranteed to be present.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

See this gist for results output.
https://gist.github.com/paddyo/c861c640a2328aaf0d09d30c103bb3dd

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

Tested in Chrome 120.
Library tested in Node 21.2.0
Browser Agent v1.248

## Additional context
Distributed tracing should be enabled in the browser application in New Relic.
The trace-parent header can be inspected for this if there any downstream issues.

Also tested in much older agent (1216) where the problem does **NOT** occur.

[TIP]:  # ( Add any other context about the problem here. )

Fix suggested in this PR:  #825

**Comment by patrickhousley** [comment]
Thanks @paddyo for reporting this issue. The browser agent has evolved a lot over the years and has had to support a number of different browsers and versions in the past. I think we can take a look back at our current browser support statement and see if the web crypto API is something that we can implement.

Just to verify, this is not causing any sort of issue for you is it? If not, I will convert this over to a feature request instead of a bug.

**Comment by paddyo** [comment]
Sorry for the misunderstanding, but this is a bug when the newrelic-browser-agent is using webcrypto api to generate its traceIds. This used to work in earlier versions of the agent that used this api, I know this because I discovered the issue when trying to upgrade our agents.  If the browser falls back to Math.random then the traceIds appear normal. I've linked to a PR that shows where the bug is and hopefully fixes it. I suspect this would affect the majority of browsers as this API is well supported these days.

From our usage of it, it is a problem as our organisation has got some DIY browser span sampling by filtering out spans whose final char doesn't match a certain character, and that character isn't 0!

**Comment by patrickhousley** [comment]
Oh yea I completely missed the PR you opened @paddyo . My bad and thanks a ton for contributing to our project. I am reviewing the PR now.

**Comment by patrickhousley** [comment]
@paddyo do you mind if I copy the code from the gist you provided into the project to make a test?

**Comment by paddyo** [comment]
No problem at all!

**Comment by patrickhousley** [comment]
PR has been merged and will be included in our next release. Thanks again @paddyo
