### ISSUE TITLE
Regression in Trace ID generation (non-random Trace ID's)

### ISSUE THREAD

**Issue by paddyo** [newrelic/newrelic-browser-agent#854]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

A regression has occurred in the Trace ID generation which causes the id to be non-random. In this case the generated Trace ID always ends in 0 (if the browser uses the webcrypto method of random value generation).

This is related to ticket: https://github.com/newrelic/newrelic-browser-agent/issues/826

The regression happened in the PR fixing ticket 826: https://github.com/newrelic/newrelic-browser-agent/pull/825 where the code was partially reverted when adding tests to the original PR.

Also, the new tests for testing the randomness do not appear to be functioning correctly, which can be demonstrated by modifying the code to generate a trace id of just 0's, which is not caught by the test.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

The trace ids can be inspected in the browser, but following the reproduction steps in https://github.com/newrelic/newrelic-browser-agent/issues/826 will show the issue in more detail

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

Generated trace ids should be completely random

## Relevant Logs / Console output

See https://github.com/newrelic/newrelic-browser-agent/issues/826 

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

Tested in Chrome 120
Library tested in Node 21.5.0
Browser Agent v1.249

## Additional context

The following PR provides a patch for this bug: https://github.com/newrelic/newrelic-browser-agent/pull/853

[TIP]:  # ( Add any other context about the problem here. )

**Comment by cwli24** [comment]
Thanks for the re-patch!
