### ISSUE TITLE
Promise wrapping breaks Promise.all() when called with an iterator

### ISSUE THREAD

**Issue by muhqu** [newrelic/newrelic-browser-agent#860]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

The promise wrapping code of the NewRelic Agent breaks `await Promise.all(...)` when it's called with an `Iterator`. Possibly the passed argument is iterated more than once. 

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
```js
map = new Map();
map.set("Foo", "Bar");
await Promise.all(map.values()) // returns [] 
```

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

It should return `["Bar"]`.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* `@newrelic/browser-agent` : `1.250.0`

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by muhqu** [comment]
Here is the problem:

https://github.com/newrelic/newrelic-browser-agent/blob/8e5a877cdf78b2f2743da8477516e1b3a7eb9f19/src/common/wrap/wrap-promise.js#L70-L78

`subPromises` is iterated when it's expanded via `[...subPromises || []]`. 
When `prevStaticFn.apply(this, arguments)` is called `arguments` still points to the same iterator that has already been used. 

The issue can be fixed like this…
```js
      WrappedPromise[method] = function (subPromises, ...otherArgs) { // use our own wrapped version of "Promise.all" and ".race" static fns
        let finalized = false
        const subPromisesArray = [...subPromises || []]
        subPromisesArray.forEach(sub => {
          this.resolve(sub).then(setNrId(method === 'all'), setNrId(false))
        })

        const origFnCallWithThis = prevStaticFn.apply(this, [subPromisesArray, ...otherArgs])
        return origFnCallWithThis
```

**Comment by patrickhousley** [comment]
Hi @muhqu . I looked into the suggested fix and unfortunately it has side effects of changing how the wrapping handles non-iterables. With the change, passing a non-iterable will resolve to an empty array instead of correctly throwing an exception. I have blocked the JIRA issue and tied it to our SPA refactor work that is currently ongoing.

**Comment by muhqu** [comment]
@patrickhousley what's the reason this bug report has been closed? I mean it's still a valid bug in latest agent or am I missing something?

**Comment by patrickhousley** [comment]
@muhqu This issue will be resolved in a future quarter with the introduction of the new soft-nav feature which does not wrap promise. The soft-nav feature will be replacing the existing spa feature.

**Comment by muhqu** [comment]
@patrickhousley basically you're saying _it would not be fixed_ and _you need to migrate to something that has not yet been released_? …not really what I was hoping to hear.

**Comment by patrickhousley** [comment]
@muhqu We (New Relic) are prioritizing the work to replace the spa feature with the soft-nav feature at this time. Since this bug will be fixed by that work, this ticket was closed. We would be happy to review a PR that solves the problem and also catches non-iterables sanely.
