### ISSUE TITLE
UNRESOLVED_IMPORT when importing to Stencil project

### ISSUE THREAD

**Issue by OuranosSkia** [newrelic/newrelic-browser-agent#864]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
When importing this module to a Stencil project, the bundler does not seem to know how to bundle newrelic. I get an UNRESOLVED_IMPORT message. Other imports to stencil appear to work properly and only newrelic's browser agent seems to have an issue.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce
(Attached a code sample or just create a new Stencil project following the Getting Started docs for it and import the browser agent)
[test-newrelic.zip](https://github.com/newrelic/newrelic-browser-agent/files/14014317/test-newrelic.zip)

After unzipping the code sample, run:
- `yarn` (or `npm i`) to install dependencies
- `yarn build` or (`npm run build`) to build the app.

When building, you will see:
```
[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           '@newrelic/browser-agent/loaders/micro-agent' is imported by src\components\my-component\my-component.tsx,
           but could not be resolved – treating it as an external dependency
```

Additionally, you can start the app with `yarn start` or `npm start`. If you start it and load the URL of the page, you will see:
```
TypeError: Failed to resolve module specifier "@newrelic/browser-agent/loaders/micro-agent". Relative references must start with either "/", "./", or "../".
```

NOTE: On some versions of TSC (or node... unsure) typescript will complain about a file `node_modules/@types/css-font-loading-module/index.d.ts` and you can work around this by opening that file and changing `string` to `FontDisplay` on any display fields. This is unrelated to the issue and this workaround is included only to help you reproduce the issue with the attached project in case you encounter it.

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior
The project builds properly with the newrelic import and, when started, properly tries to load the newrelic agent (it's not configured in this example, but I should see it try).

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment
This is noticed across various environments both Windows and OSX. 

The project uses [Stencil](https://stenciljs.com/)
[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by patrickhousley** [comment]
@OuranosSkia This issue is something that the Stencil project will need to fix. I believe [this](https://github.com/ionic-team/stencil/issues/3605) issue is what they need to resolve. Until that is done, you can change your import statement to fix your project:

```
// Instead of importing like this:
import { MicroAgent } from "@newrelic/browser-agent/loaders/micro-agent";

// Import like this
import { MicroAgent } from "@newrelic/browser-agent/src/loaders/micro-agent";
```

I have also opened a [PR](https://github.com/newrelic/newrelic-browser-agent/pull/887) to add the types mappings for our EMS distribution. Once that is merged and release, you will be able to use `import { MicroAgent } from "@newrelic/browser-agent/dist/esm/loaders/micro-agent";` without getting typescript types errors.

Either import should work but importing from `src` will pull in our raw ES2019+ code. The ESM dist is transcoded to match our [browser support statement](https://docs.newrelic.com/docs/browser/new-relic-browser/getting-started/compatibility-requirements-browser-monitoring/#browser-types).

**Comment by OuranosSkia** [comment]
Thanks for the detailed breakdown of this and a workaround! I also have a similar issue on the Stencil side, so I will update it there with what you found.

**Comment by shaikhspear16** [comment]
This is resolved in the new StencilJs release [https://github.com/ionic-team/stencil/issues/3605 issue ](https://github.com/stenciljs/core/releases/tag/v4.28.0)
