### ISSUE TITLE
Error `TypeError: Cannot create property 'NREUM' on boolean 'false'` when instantiating the agent on a next.js application

### ISSUE THREAD

**Issue by dennislo** [newrelic/newrelic-browser-agent#865]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
We are seeing an error `TypeError: Cannot create property 'NREUM' on boolean 'false'` when instantiating the agent on a next.js application.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
Following steps here https://www.npmjs.com/package/@newrelic/browser-agent#instantiating-the-agent to instantiate the agent.

1. We added the relevant newrelic browser options, calling `new BrowserAgent(options);` inside `_document.tsx` file:
```
import { BrowserAgent } from '@newrelic/browser-agent/loaders/browser-agent';

import Document, { Html, Main, NextScript } from 'next/document';

class AppDocument extends Document {
  render() {
    // Populate using values in copy-paste JavaScript snippet.
    const options = {
      init: {
        distributed_tracing: { enabled: true },
        privacy: { cookies_enabled: true },
        ajax: { deny_list: ['bam.nr-data.net'] },
      },
      info: {
        beacon: 'bam.nr-data.net',
        errorBeacon: 'bam.nr-data.net',
        licenseKey: 'NRBR-11111',
        applicationID: '11111',
        sa: 1,
      },
      loader_config: {
        accountID: '11111',
        trustKey: '11111',
        agentID: '11111',
        licenseKey: 'NRBR-11111',
        applicationID: '11111',
      },
    };

    // The agent loader code executes immediately on instantiation.
    new BrowserAgent(options);

    return (
      <Html>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default AppDocument;

```
2. When starting the app locally we see the error:
```
Server Error
TypeError: Cannot create property 'NREUM' on boolean 'false'

This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )
We expect the browser agent to be instantiated and integrated properly.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )
```
Server Error
TypeError: Cannot create property 'NREUM' on boolean 'false'

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
gosNREUM
file:///Users/dlo/mns/onyx/node_modules/.pnpm/@newrelic+browser-agent@1.250.0/node_modules/@newrelic/browser-agent/dist/cjs/common/window/nreum.js (26:32)
gosNREUMOriginals
file:///Users/dlo/mns/onyx/node_modules/.pnpm/@newrelic+browser-agent@1.250.0/node_modules/@newrelic/browser-agent/dist/cjs/common/window/nreum.js (58:12)
Object.<anonymous>
file:///Users/dlo/mns/onyx/node_modules/.pnpm/@newrelic+browser-agent@1.250.0/node_modules/@newrelic/browser-agent/dist/cjs/common/config/state/originals.js (8:48)
Module._compile
node:internal/modules/cjs/loader (1256:14)
Module._extensions..js
node:internal/modules/cjs/loader (1310:10)
Module.load
node:internal/modules/cjs/loader (1119:32)
Module._load
node:internal/modules/cjs/loader (960:12)
Module.require
node:internal/modules/cjs/loader (1143:19)
Hook._require.Module.require
file:///Users/dlo/mns/onyx/node_modules/.pnpm/require-in-the-middle@7.2.0/node_modules/require-in-the-middle/index.js (188:39)
require
node:internal/modules/cjs/helpers (119:18)
Object.<anonymous>
file:///Users/dlo/mns/onyx/node_modules/.pnpm/@newrelic+browser-agent@1.250.0/node_modules/@newrelic/browser-agent/dist/cjs/common/config/config.js (70:18)
Module._compile
```
## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* Browser name and version: 
  * Chrome, Version 120.0.6099.234 (Official Build) (arm64)
* Operating System and version: 
  * macOS Monetery Version 12.6
* NPM Packages
  * https://github.com/vercel/next.js v13.4.3
  * https://github.com/facebook/react v18.2.0
  * https://github.com/newrelic/newrelic-browser-agent v1.250.0
  * https://github.com/newrelic/newrelic-node-nextjs v0.7.0

## Additional context

[TIP]:  # ( Add any other context about the problem here. )
![NREUM-boolean-false-error](https://github.com/newrelic/newrelic-browser-agent/assets/598330/6e8e29b0-2002-4522-822c-17aafcc51261)

**Comment by maria-kravtsova** [comment]
I just run into this issue. To fix it, I imported the library dynamically in a useEffect:

  useEffect(() => {
    if (typeof window !== "undefined") {
      (async () => {
        const { BrowserAgent } = await import(
          "@newrelic/browser-agent/loaders/browser-agent"
        );
        new BrowserAgent({

**Comment by patrickhousley** [comment]
@maria-kravtsova Thanks for the update. We are going to take that as the answer to this issue. We do not support initializing the browser agent outside a browser/worker context.

**Comment by davidhu2000** [comment]
```patch
diff --git a/dist/cjs/common/window/nreum.js b/dist/cjs/common/window/nreum.js
index 41e9c1da2bea057a601fa7e460057ff4c848cd87..7b1f284bec9e01514e3abb666f5558ab579e8f37 100644
--- a/dist/cjs/common/window/nreum.js
+++ b/dist/cjs/common/window/nreum.js
@@ -22,6 +22,7 @@ const defaults = {
 };
 exports.defaults = defaults;
 function gosNREUM() {
+  if (typeof _runtime.globalScope === 'boolean') return {}
   if (!_runtime.globalScope.NREUM) {
     _runtime.globalScope.NREUM = {};
   }
diff --git a/dist/esm/common/window/nreum.js b/dist/esm/common/window/nreum.js
index f50959d514031be72d3c292beb1de7531a9fd9a7..69e54a34343c86abbd9751a9aedcdc9a5f2a84b7 100644
--- a/dist/esm/common/window/nreum.js
+++ b/dist/esm/common/window/nreum.js
@@ -5,6 +5,7 @@ export const defaults = {
   errorBeacon: 'bam.nr-data.net'
 };
 export function gosNREUM() {
+  if (typeof globalScope === 'boolean') return {}
   if (!globalScope.NREUM) {
     globalScope.NREUM = {};
   }
diff --git a/src/common/window/nreum.js b/src/common/window/nreum.js
index 47fb9afd150311463388ff36e08c2fb396cefa90..9fe7fc4e6e4d3145e8e0348842b26dceda790a33 100644
--- a/src/common/window/nreum.js
+++ b/src/common/window/nreum.js
@@ -7,6 +7,7 @@ export const defaults = {
 }
 
 export function gosNREUM () {
+  if (typeof globalScope === 'boolean') return {}
   if (!globalScope.NREUM) {
     globalScope.NREUM = {}
   }
```

@patrickhousley @dennislo @maria-kravtsova this is what i ended up doing, patching the function to check if globalScope is a boolean. It has worked well for my nextjs app.

**Comment by Jordaneisenburger** [comment]
old relic.

**Comment by zdarovka** [comment]
This is still an issue. I am getting the same error.
