### ISSUE TITLE
Replace or mask sensitive segments of a URL path

### ISSUE THREAD

**Issue by sskilbred** [newrelic/newrelic-browser-agent#87]
## Summary
New Relic Browser collect lots of information about URLs (page urls, ajax-request urls, etc.), and sometimes these can contain information deemed sensitive (either by the authorities or internal company security). Currently there is no way actively mask or replace the segments of these URLs.

## Desired Behavior

Ideally, the browser agent API would be extended with functions to replace all URLs with specific patterns, eg. nreum.replaceURL('regex-pattern', replacement). These pattern-replacement pairs would have to be checked for all the URLs being reported to New Relic (including URLs for page-views, browser-interactions, ajax-requests and session-traces).

## Possible Solution (field solution)

We created a field solution  for this, where we extended the compiled agent and manually added the patterns to the loader.js. The agent.js would then call a specific function before storing the url, and the function would check for patterns and replace where matched are found. I have attached both loader and agent (unminified).
In the loader.js you can find the code at the bottom of the file (line 2392). There are 2 cleaner-functions (used in the agent.js) + an array of regex-patterns and -replace entries.
[agent+loader.zip](https://github.com/newrelic/newrelic-browser-agent/files/6877686/agent%2Bloader.zip)

## Additional comments

Although the field solution works, it isn't ideal. Upgrades would have to be extended, source-files changed, etc. A productised solution would be useful for any customer needing to mask or even group their URLs in a custom manner. The agent API would solve the inconvenience of having to re-implement after each agent upgrade.

**Comment by coreyarnold** [comment]
completed

**Comment by william-will-angi** [comment]
@coreyarnold Would you mind providing a bit more context? I am trying to find the information through new relic docs, but I'm not finding anything that suggests you're able to mask parts of the url

**Comment by jdelStrother** [comment]
It wasn't entirely obvious, but I'm assuming they're referring to NREUM.init.obfuscate - https://docs.newrelic.com/docs/browser/new-relic-browser/configuration/obfuscate-browser-agent-data/
