### ISSUE TITLE
NewRelic Browser Agent (v1.251.1) interfering with Googlebot crawling / Google Search Console

### ISSUE THREAD

**Issue by sundquistm** [newrelic/newrelic-browser-agent#883]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

We're seeing Googlebot/Google Search Console picking up malformed URLs from NewRelic. This has been ongoing for at least a month and seemingly over the past 1-2+ releases.

As I understand it, this issue was fixed in Feb. 2023 per v1225 https://docs.newrelic.com/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1225/#resolve-google-indexing-of-agent-relative-paths . Possible regression bug?

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

Use Google Search Console to find invalid Page URLs such as:
- `/the-page/metrics/aggregate`
- `/the-page/page_view_event/aggregate`
- `/the-page/spa/aggregate`
- `/the-page/page_view_timing/aggregate`

## Expected Behavior

It doesn't do that.

## Relevant Logs / Console output

N/A

## Your Environment

Browser Agent Version:
  - Resource: https://js-agent.newrelic.com/nr-rum-1.251.1.min.js
  - Payload: `v: 1.251.1`

## Additional context

N/A

**Comment by patrickhousley** [comment]
Hi @sundquistm and thanks for bring this issue to our attention. We have actually addressed this concern a few times. This is an issue with the google bot assuming strings in script tags that look like URIs should be indexed. Please contact google search support team for this issue. Below are some links to help provide context and guidance.

https://github.com/newrelic/newrelic-browser-agent/issues/419
https://docs.newrelic.com/docs/browser/new-relic-browser/troubleshooting/google-indexing-unknown-paths/

**Comment by sundquistm** [comment]
@patrickhousley Thanks. That makes sense.
