### ISSUE TITLE
Meet New Standards for CLS

### ISSUE THREAD

**Issue by rr0214** [newrelic/newrelic-browser-agent#89]
**Background**

CLS captures how much the page shifts and how often. There are use cases, especially for single page applications, where the page can be open for a very long time which results in a score that is too high. Google therefore has capped that to account for the maximum layout shift window aka capturing the most frustrating burst of layout shift on the page.

**What will we do**

This effort is to match the new standard for our CLS reporting.

**Customer & business value**

This is an iterating of work for capture more data/better signal. It is also work we need to do to be on top of latest key metrics for RUM monitoring.

<br/>

**Comment by metal-messiah** [comment]
Tickets can be tracked [here](https://github.com/newrelic/newrelic-browser-agent/projects/2)
