### ISSUE TITLE
Missing data on Errors and Ajax page

### ISSUE THREAD

**Issue by UserWangjn** [newrelic/newrelic-browser-agent#914]
I couldn't report JS error and Ajax, I tried the following:
1. The unhandledrejection event. click the function
![image](https://github.com/newrelic/newrelic-browser-agent/assets/37054910/a6145e8e-88fc-4ebb-a79a-6e9c2b5b702f)
2. The Error Event.click the function
![image](https://github.com/newrelic/newrelic-browser-agent/assets/37054910/23752de2-9817-4027-8536-69fcd50d399d)
3. Use the noticeError.click the function
![image](https://github.com/newrelic/newrelic-browser-agent/assets/37054910/d3d2e9ad-c8f4-4519-a881-a60d7c85b7a4)
4.Ajax I tried xhr and fetch

Install the browser agent,I tried two ways,The Pro And Pro + SPA:
![image](https://github.com/newrelic/newrelic-browser-agent/assets/37054910/76635f1a-6cc4-4ddf-8c82-c63298dbb337)
![image](https://github.com/newrelic/newrelic-browser-agent/assets/37054910/a168852b-cb48-4c58-add1-e25c35881b2c)

**Comment by UserWangjn** [comment]
> https://new-relic.atlassian.net/browse/NR-247890

![image](https://github.com/newrelic/newrelic-browser-agent/assets/37054910/0cfdbd38-1677-45e0-8b23-8d5d7dd4365d)

**Comment by patrickhousley** [comment]
@UserWangjn please reach out to our New Relic Support. You can use our [community site](https://support.newrelic.com/s/) to contact them directly or post in our community forums.
