### ISSUE TITLE
Running the NR agent in web worker instead of main thread

### ISSUE THREAD

**Issue by tibineagu** [newrelic/newrelic-browser-agent#915]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

Some of the functionality of the browser agent could be delegated to a web worker.

We tried running the JavaScript snippet script (as obtained via the [docs](https://docs.newrelic.com/docs/browser/browser-monitoring/installation/install-browser-monitoring-agent/)) through [Partytown](https://partytown.builder.io/), but there are many dependencies on the global `window` object that don't translate well to running in the worker context.

## Desired Behavior

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

It would be very useful for the community if you could provide documentation and example of a setup where the NR agent is run via web workers.

This will obviously come with caveats but there will be use-cases where the benefits might outweigh the deficits.

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

While we have not used the `browser-agent` library at all (and are instead relying on the JS snippet), I wonder if an equivalent set-up can be achieved by using multiple micro agents, some in worker mode, and some on the main thread.

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

CWV have become increasingly important in today's SEO ecosystem, and any bit of performance that can be wrestled back from third-party scripts is a welcome improvement. With the introduction of INP as a stable core web vital metric this month, many developers are be looking into every possible avenue to increase performance.

**Comment by patrickhousley** [comment]
Hi @tibineagu and thanks for opening this issue. Unfortunately we do not officially support running the agent in a worker context or even running part of the agent in a worker context. I would suggest reaching out in our [forums](https://support.newrelic.com/s/) and/or your New Relic sales/support contact.
