### ISSUE TITLE
Track CSP Violations out of the box

### ISSUE THREAD

**Issue by metal-messiah** [newrelic/newrelic-browser-agent#92]
## Summary
NR Browser Agent could (and should) track CSP errors out of the box. This would likely be a relatively simple implementation and could provide insight on malicious frontend attacks / vulnerabilities.

## Desired Behavior
Implementing the NR Browser Agent should capture and forward CSP violation errors to `.noticeError()` automatically.

## Possible Solution
Subscribe to the DOM Event `securitypolicyviolation` and have the callback issue a `newrelic.noticeError(...)` with relevant info.

## Additional context
Customers could gain insight on malicious activity and vulnerabilities.

##use cases/questions
Shows up as an error in console and not in NR1
How does it show up in the UI given it happens outside of a javascript error
Would you want to track it in a RUM environment
How often CSP blocked something: example: tried to run agent extension and it gets blocked by CSP

**Comment by rr0214** [comment]
Enhancement proposal will be evaluated based on customer feedback

**Comment by rr0214** [comment]
We could likely add the possible solution as information in our docs. Let's get more context on customer interest.

**Comment by villelahdenvuo** [comment]
There's also https://report-uri.com/ would be nice to be able to create an endpoint in New Relic, but also having the Agent do it automatically is also very nice. I support this idea.

**Comment by justinh00k** [comment]
Was just setting up CSP and hoping NewRelic would know what to use as report-uri.
