### ISSUE TITLE
Support for Svelte

### ISSUE THREAD

**Issue by josiahwitheford** [newrelic/newrelic-browser-agent#923]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

I found a closed issue [263](https://github.com/newrelic/newrelic-browser-agent/issues/263) from a couple of years ago. Wondering if there is any chance of supporting svelte projects via the node APM agent now, or is the recommended approach to just use the copy-paste method?

I am needing to support multiple applications across different environments (dev, staging, prod) and the copy paste method gets messy with needing to swap out application ID's at build time instead of being able to configure it via environment variables at runtime, so I would prefer not to go this route if at all possible.

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

## Desired Behavior

It would be great if the NodeJS APM agent is able to integrate with svelte projects, or if there could be some explanation provided for why this feature request was previously declined.

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by patrickhousley** [comment]
Hey @josiahwitheford Thanks for reaching out. We technically do not provide support for specific libraries or frameworks. There are just too many of them with their own quarks and the landscape just changes too rapidly. Instead, our stance is that we try to be agnostic to libraries and frameworks and "just work". We hit snags every now and then and we try to [document](https://docs.newrelic.com/docs/browser/single-page-app-monitoring/troubleshooting/nextjs-app-router-links-broken/) them when we are made aware of them.

For svelte, I  don't know of any specific reason the agent, npm package or copy+paste, would not work. The issue you referenced had no real content around what support was being asked for, what was not working, or what was lacking. For your use-case, at least for what you have provided, I would recommend just giving the npm agent a try and/or maybe taking a look at using our [NerdGraph APIs](https://docs.newrelic.com/docs/apis/nerdgraph/examples/combining-npm-nerdgraph/) to help make your configuration/build easier.

I am going to close this issue for now. Feel free to continue to reply but if you do run into a specific issue that you need help with, please open a new ticket. We also have a pretty extensive [community](https://support.newrelic.com/s/) that might also be able to help with any questions or implementation guides. Finally, always feel free to reach out to your New Relic support team.
