### ISSUE TITLE
Documentation for CSP

### ISSUE THREAD

**Issue by rr0214** [newrelic/newrelic-browser-agent#94]
## Summary

There have been  questions on CSP this summer and support shared the self hosting option/workaround  to several customers which has been useful. 

## Desired Behavior

Let's put this solution into our github repo for reference. 

## Possible Solution

[csp-v2-host-install-browser-agent (1).pdf](https://github.com/newrelic/newrelic-browser-agent/files/7002984/csp-v2-host-install-browser-agent.1.pdf)

**Comment by rr0214** [comment]
I will add this information to Explorer's hub and meet with the docs team on their long term approach to workarounds

**Comment by patrickhousley** [comment]
Closing. The CSP guidance was updated with the release of 1.247.0 when we implemented support for `nonce` and SRI.
