### ISSUE TITLE
[bug] newrelic 1.255.0 does not appear to autostart collection

### ISSUE THREAD

**Issue by FranciscoKloganB** [newrelic/newrelic-browser-agent#952]
## Description

In our platform, when the user accesses the web page, he sees a instrumentation consent screen that allows him to opt-out of non-essential tracking scripts.

When the user opts-out, we still create a browser-agent instance, but the only features that are initiated are the ones we configured to be "autoStart" in the agent configuration (**JavaScriptError** and **AjaxRequest**). We only call the agent's init method explicitly, to start other features, if the user accepts certain parameters.

When using browser-agent SDK at version 1.252.0, this works as intended. The events **JavaScriptError** and **AjaxRequest** always reach our newrelic platform, regardless of user choice, but other actions such has **BrowserInteraction** only reach newrelic when the user says "yes" to some field.

I have not tried `1.253.0` nor `1.254.0`, but an update to `1.255.0`, causes an issue where when the user accepts (BrowserAgent init method is called explicitly) everything works as expected, but if he rejects (i.e., only `autoStart` features should be initiated) our newrelic platform receives absolutely no events.

## Steps to Reproduce

- Create a simple SPA application
- Create a newrelic configuration which includes a few BrowserAgent features (see code snippet below)
- Install SDK version 1.252
- Run the application `ajax` and `jserrors` **are** captured
- Do not explicitly call `init` method of the Browser Agent.
- Install SDK version 1.255 
- Do not explicitly call `init` method of the Browser Agent.
- Run the application `ajax` and `jserrors`  **are not**  captured

```ts
export function createNewrelicConfig({
    accountId,
    agentId,
    applicationId,
    enabled = true,
    licenseKey,
    trustKey,
}: NewrelicConfigParams) {
    const agentID = enabled ? agentId : '__local_agent__';
    const applicationID = enabled ? applicationId : '__local_application__';

    return {
        browserAgent: {
            enabled,
            options: {
                info: {
                    applicationID,
                    licenseKey,
                    beacon: 'bam.nr-data.net',
                    errorBeacon: 'bam.nr-data.net',
                    sa: 1,
                },
                init: {
                    privacy: {
                        cookies_enabled: false,
                    },
                    ajax: {
                        autoStart: true,
                        enabled: true,
                        deny_list: ['bam.nr-data.net'],
                    },
                    distributed_tracing: {
                        autoStart: true,
                        enabled: true,
                    },
                    jserrors: {
                        autoStart: true,
                        enabled: true,
                    },
                    metrics: {
                        autoStart: false,
                        enabled: true,
                    },
                    page_action: {
                        autoStart: false,
                        enabled: true,
                    },
                    page_view_event: {
                        autoStart: false,
                        enabled: true,
                    },
                    page_view_timing: {
                        autoStart: false,
                        enabled: true,
                    },
                    session_replay: {
                        autoStart: false,
                        enabled: false,
                    },
                    session_trace: {
                        autoStart: false,
                        enabled: true,
                    },
                    spa: {
                        autoStart: false,
                        enabled: true,
                    },
                },
                loaderConfig: {
                    accountID: accountId,
                    agentID,
                    applicationID,
                    licenseKey,
                    trustKey,
                },
            },
        },
    } as const;
}
```

## Expected outcome

Auto started features are captured regardless of wether the BrowserAgent init method is explicitly called or not.

## Your Environment

Not relevant.

**Comment by patrickhousley** [comment]
@FranciscoKloganB thanks for reporting this issue. Could you provide a snippet or example app that shows how you are initializing the agent with the config from your example? I am confused because at no point should you ever need to explicitly call the `init` function on the agent. Simply instantiate the agent class with the given config will start the capturing and reporting of data for feature that have `autoStart` enabled. For the remaining features, there is a [`start`](https://docs.newrelic.com/docs/browser/new-relic-browser/browser-apis/start/) API that you can and should use.

**Comment by FranciscoKloganB** [comment]
Hey @patrickhousley, first and foremost, sorry for the delayed response.

> I have not tried 1.253.0 nor 1.254.0, but an update to 1.255.0, causes an issue where when the user accepts (BrowserAgent init method is called explicitly) everything works as expected, but if he rejects (i.e., only autoStart features should be initiated) our newrelic platform receives absolutely no events.

This was an unfortunate description. I was trying to simplify the use-case description, we actually use start methods. At this point it would be difficult to share a live reproduction, when I have some spare time I can try to create a Stackblitz exemplifying how we are doing this. For now the best I can do is paste some of the code we got. Our newrelic is part of a broader monitoring/tracking strategy. 

We have a consent service and the idea is that a newrelic agent **is always** created with Ajax and JavaScriptError which ar autoStarted. However, the remaining functionalities are only started if a user consents to some type of data collection. We use a custom agent that extends Agent class (very, very, very similar to `BrowserAgent` source code) and then an Angular `AnalyticsService` which integrates with `AnalyticsAgent` and other tools manages the integration with that `ConsentService` I talked about. See the code snippets below.

```ts
export class AnalyticsAgent extends Agent {
    private instrumentingNonEssentials: boolean;

    constructor(options: Record<string, unknown>, agentId: string) {
        super(
            {
                ...options,
                features: [Ajax, JSErrors, Metrics, PageAction, PageViewEvent, PageViewTiming, SessionTrace, Spa],
                loaderType: 'browser-agent',
            },
            agentId,
        );

        this.instrumentingNonEssentials = false;
    }

    public enableFeatures() {
        Object.keys(this.features).forEach(featureName => {
            if (this.featureAvailable(featureName)) {
                this.features[featureName].enabled = true;
            }
        });

        this.instrumentingNonEssentials = true;

        return this;
    }

    public disableNonEssentialFeatures() {
        if (this.instrumentingNonEssentials && typeof window !== 'undefined') {
            window.location.reload();
        }

        return this;
    }

    public featureAvailable(featureName: string) {
        return this.config['init'][featureName]?.enabled === true;
    }
}

@Injectable({
    providedIn: 'root',
})
export class AnalyticsService implements OnDestroy, ITracker {
    private agent: AnalyticsAgent | undefined;

    constructor(private cookieConsentService: CookieConsentService) {
        const appConfig = inject(APP_CONFIG);

        this.config = appConfig.newrelic.browserAgent.options;
        this.available = appConfig.newrelic.browserAgent.enabled;

        if (this.available) {
            this.agent = this.createAgent();
            this.userConsentSubscription = this.cookieConsentService.userConsent$
                .pipe(debounceTime(125))
                .subscribe(value => {
                    this.onUserConsent(value);
                });
        }
    }

    private createAgent() {
        this.agent = new AnalyticsAgent(this.config, this.config['loaderConfig']['agentID']);

        return this.agent;
    }

    private restart() {
        this.agent.enableFeatures().start();
    }

    private start() {
        this.createAgent().enableFeatures().start();
    }

    private stop() {
        this.agent.disableNonEssentialFeatures();
    }

    private onUserConsent(current: UserConsentValue) {
        if (!this.available) {
            return;
        }

        const activeCategory = current[this.category] === true;
        const activeService = current.services[this.category].includes(this.id);
        const shouldStart = activeCategory && activeService;

        if (shouldStart) {
            if (!this.agent) {
                return this.start();
            }

            return this.restart();
        }

        if (this.agent) {
            return this.stop();
        }
    }
}
```

**Comment by patrickhousley** [comment]
@FranciscoKloganB thanks for clarifying and for the code fragments. Maybe we can narrow down the issue to make it easier to find.

- Can you try the versions between 1.252.0 and 1.255.0 to see where the issue was introduced? 
- Can you remove the `agentId` from your class. That is a randomly generated ID internally and you should not set that.

One thing I might suggest, our `BrowserAgent` class was not wrote with the intention of being extended. I wonder if that might be part of the problem. I wonder if you were to change `AnalyticsAgent` so it encapsulates the `BrowserAgent` instance instead of extending it, if you would be able to make this work.

Note to self, quick link to 1.252.0..1.255.0 diff: https://github.com/newrelic/newrelic-browser-agent/compare/v1.252.0...v1.255.0

**Comment by FranciscoKloganB** [comment]
I'll come to you tomorrow on the "in between versions" recording data or not.

Note that I am extending the `Agent` class not the `BrowserAgent` (as recommended [here](https://github.com/newrelic/newrelic-browser-agent?tab=readme-ov-file#composing-a-custom-agent-with-selected-feature-modules)). I only looked upon the `BrowserAgent` class for inspiration.

The reason I added the `agentId` it's because the Agent class changed signature in `1.253` - `1.255.0`. See this screenshot:

![image](https://github.com/newrelic/newrelic-browser-agent/assets/25959244/c2512c26-d1db-4bbe-b5d6-65b21bcd91b1)

The class constructors expects a second argument without marking it as optional. Causing the class on the left (custom `AnalyticsAgent`) TypeScript to shout at me saying that it expects a second argument. So I added one, even tho looking at the source code, it's a variable that is not used. However, if I go back to `1.252.0`, the `Agent` class has a different constructor.

![image](https://github.com/newrelic/newrelic-browser-agent/assets/25959244/d43ca49f-a23f-49e1-8d81-7e81277603c1)

**Comment by FranciscoKloganB** [comment]
Pinpointed the issue to @newrelic/browser-agent@1.254.0

Using with 1.253.0 `AjaxRequests` and `JavaScriptError` **are** autoStarted has specified in the configuration object; The problem I mentioned in the OP begins version 1.254.0.

However, the screenshots above show that in version 1.253 the signature of the Agent class constructor changed and expects the child classes to pass an `agentId`, which is then passed to `AgentBase`.

**Comment by patrickhousley** [comment]
@FranciscoKloganB Thanks for the additional information and pinning down the version the issue presented in. I will try setting up some tests locally. I think I have an idea as to what the issue might be. I also have a few additional recommendations regarding your implementation.

>Note that I am extending the Agent class not the BrowserAgent (as recommended [here](https://github.com/newrelic/newrelic-browser-agent?tab=readme-ov-file#composing-a-custom-agent-with-selected-feature-modules)).
You should use the `Agent` class and not the `BrowserAgent` class as the link you provided explains. However, the docs do not speak to extending the class, simply instantiating it. I still think you might want to try using a composition pattern instead of inheritance for your AnalyticsAgent class. (Not that that would solve your issue.)

> `this.features[featureName].enabled = true;`
This doesn't make a lot of sense given your configuration. All the features except for session replay are enabled, just not auto-started. Realistically, this should not be needed. You just need to call the `start()` API on the agent. If you want to start a single feature, pass a string with the feature name, multiple features, use an array of strings, or all features that are enabled, undefined like you have it.

**Comment by FranciscoKloganB** [comment]
Thanks for the suggestions, I will definitely take some time to apply at least the 2nd suggestion.

**Comment by FranciscoKloganB** [comment]
**side question:** do you have any idea why `firefox` and `safari v17` refuse to send events to newrelic when running within an iframe? I've disabled browser protections that come by default; events are registred in chrome. We are facing this issue on a different application than the one I mentioned.

The dashboard app (the one we have been talking about so far) runs perfectly in all browsers. However, an exact copy of the implementation (which used to be just a copy/pasted umd script), when running within a iframe which is rendered when "customer developers" call them through a  web sdk, only report when browser is chrome or edge.

I can open a different ticket regarding this topic, if you have absolutly no idea why this could be the case.

**Comment by patrickhousley** [comment]
Lets move that to a different issue.

**Comment by patrickhousley** [comment]
Hey @FranciscoKloganB sorry we did not see the issue last week but the problem is actually in your configuration and, the fact that your scenario was working was actually a bug. We fixed a bug in 1.254.0 that allowed the JSErrors and Ajax features to run independent of the PageViewEvent (PVE) feature. The agent requires the PVE feature to execute before any of the other features will harvest data. In your configuration, change `page_view_event.autoStart` to be `true` or none of the feature will harvest data.

**Comment by patrickhousley** [comment]
Also note, we are looking at modifying the `start` API which is currently part of a limited preview to not take any parameter. Essentially, calling `start` will start all enabled features that have `autoStart: false`.

**Comment by FranciscoKloganB** [comment]
Hey Hey @patrickhousley no worries. We can keep busy. :)

I will open a ticket to resolve problems on our side.

**Comment by patrickhousley** [comment]
> Any other feature other than page_view_event must be enabled for AjaxRequests/JavaScriptError to work out of the box?

Nope. The PVE feature is the only one that is required in the agent. Everything else is at your descretion.

> Applied suggested changes. Everything appears operational.

Awesome. I will close out this issue. Have a good week.
